# TASK 6:Combine all 3 into one Knowledge Base

In [3]:
import sys
!{sys.executable} -m pip install kagglehub pandas

Collecting kagglehub
  Using cached kagglehub-1.0.2-py3-none-any.whl.metadata (40 kB)
Requirement already satisfied: pandas in c:\users\famil\anaconda3\lib\site-packages (2.1.4)
Collecting kagglesdk<1.0,>=0.1.22 (from kagglehub)
  Using cached kagglesdk-0.1.33-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: packaging in c:\users\famil\anaconda3\lib\site-packages (from kagglehub) (23.2)
Requirement already satisfied: pyyaml in c:\users\famil\anaconda3\lib\site-packages (from kagglehub) (6.0.1)
Requirement already satisfied: requests in c:\users\famil\anaconda3\lib\site-packages (from kagglehub) (2.33.0)
Requirement already satisfied: tqdm in c:\users\famil\anaconda3\lib\site-packages (from kagglehub) (4.67.3)
Collecting numpy<2,>=1.23.2 (from pandas)
  Downloading numpy-1.26.4-cp311-cp311-win_amd64.whl.metadata (61 kB)
     ---------------------------------------- 0.0/61.0 kB ? eta -:--:--
     ---------------------------------------- 61.0/61.0 kB 1.6 MB/s eta 0:00:00
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\famil\anaconda3\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\famil\anaconda3\lib\site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\famil\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: protobuf in c:\users\famil\anaconda3\lib\site-packages (from kagglesdk<1.0,>=0.1.22->kagglehub) (5.29.6)
Requirement already satisfied: six>=1.5 in c:\users\famil\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\famil\anaconda3\lib\site-packages (from requests->kagglehub) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\famil\anaconda3\lib\site-packages (from requests->kagglehub) (3.11)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\famil\anaconda3\lib\site-packages (from requests->kagglehub) (2.0.7)
Requirement already satisfied: certifi>=2023.5.7 in c:\users\famil\anaconda3\lib\site-packages (from requests->kagglehub) (2026.2.25)
Requirement already satisfied: colorama in c:\users\famil\anaconda3\lib\site-packages (from tqdm->kagglehub) (0.4.6)
Using cached kagglehub-1.0.2-py3-none-any.whl (70 kB)
Using cached kagglesdk-0.1.33-py3-none-any.whl (243 kB)
Downloading numpy-1.26.4-cp311-cp311-win_amd64.whl (15.8 MB)
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB 8.6 MB/s eta 0:00:02
   - -------------------------------------- 0.5/15.8 MB 7.8 MB/s eta 0:00:02
   - -------------------------------------- 0.7/15.8 MB 6.6 MB/s eta 0:00:03
   -- ------------------------------------- 1.1/15.8 MB 7.2 MB/s eta 0:00:03
   --- ------------------------------------ 1.5/15.8 MB 6.9 MB/s eta 0:00:03
   ---- ----------------------------------- 1.8/15.8 MB 7.2 MB/s eta 0:00:02
   ----- ---------------------------------- 2.1/15.8 MB 7.1 MB/s eta 0:00:02
   ------ --------------------------------- 2.4/15.8 MB 7.1 MB/s eta 0:00:02
   ------ --------------------------------- 2.7/15.8 MB 7.1 MB/s eta 0:00:02
   -------- ------------------------------- 3.2/15.8 MB 7.3 MB/s eta 0:00:02
   --------- ------------------------------ 3.7/15.8 MB 7.5 MB/s eta 0:00:02
   ---------- ----------------------------- 4.2/15.8 MB 7.8 MB/s eta 0:00:02
   ----------- ---------------------------- 4.5/15.8 MB 7.8 MB/s eta 0:00:02
   ------------- -------------------------- 5.2/15.8 MB 8.1 MB/s eta 0:00:02
   -------------- ------------------------- 5.5/15.8 MB 8.0 MB/s eta 0:00:02
   --------------- ------------------------ 6.1/15.8 MB 8.5 MB/s eta 0:00:02
   ---------------- ----------------------- 6.5/15.8 MB 8.3 MB/s eta 0:00:02
   ----------------- ---------------------- 6.7/15.8 MB 8.1 MB/s eta 0:00:02
   ----------------- ---------------------- 7.0/15.8 MB 8.1 MB/s eta 0:00:02
   ------------------ --------------------- 7.3/15.8 MB 7.9 MB/s eta 0:00:02
   ------------------- -------------------- 7.5/15.8 MB 7.8 MB/s eta 0:00:02
   ------------------- -------------------- 7.7/15.8 MB 7.6 MB/s eta 0:00:02
   ------------------- -------------------- 7.9/15.8 MB 7.5 MB/s eta 0:00:02
   -------------------- ------------------- 8.1/15.8 MB 7.3 MB/s eta 0:00:02
   --------------------- ------------------ 8.3/15.8 MB 7.3 MB/s eta 0:00:02
   --------------------- ------------------ 8.6/15.8 MB 7.1 MB/s eta 0:00:02
   ---------------------- ----------------- 8.8/15.8 MB 7.0 MB/s eta 0:00:01
   ---------------------- ----------------- 9.0/15.8 MB 6.9 MB/s eta 0:00:01
   ----------------------- ---------------- 9.3/15.8 MB 6.9 MB/s eta 0:00:01
   ------------------------ --------------- 9.5/15.8 MB 6.9 MB/s eta 0:00:01
   ------------------------ --------------- 9.8/15.8 MB 6.9 MB/s eta 0:00:01
   ------------------------- -------------- 10.1/15.8 MB 6.8 MB/s eta 0:00:01
   -------------------------- ------------- 10.4/15.8 MB 6.8 MB/s eta 0:00:01
   -------------------------- ------------- 10.6/15.8 MB 6.7 MB/s eta 0:00:01
   --------------------------- ------------ 10.8/15.8 MB 6.7 MB/s eta 0:00:01
   --------------------------- ------------ 11.0/15.8 MB 6.6 MB/s eta 0:00:01
   ---------------------------- ----------- 11.2/15.8 MB 6.5 MB/s eta 0:00:01
   ----------------------------- ---------- 11.5/15.8 MB 6.5 MB/s eta 0:00:01
   ----------------------------- ---------- 11.8/15.8 MB 6.4 MB/s eta 0:00:01
   ------------------------------ --------- 12.0/15.8 MB 6.4 MB/s eta 0:00:01
   ------------------------------- -------- 12.3/15.8 MB 6.4 MB/s eta 0:00:01
   ------------------------------- -------- 12.5/15.8 MB 6.3 MB/s eta 0:00:01
   -------------------------------- ------- 12.7/15.8 MB 6.2 MB/s eta 0:00:01
   -------------------------------- ------- 12.9/15.8 MB 6.1 MB/s eta 0:00:01
   --------------------------------- ------ 13.0/15.8 MB 6.0 MB/s eta 0:00:01
   --------------------------------- ------ 13.2/15.8 MB 5.9 MB/s eta 0:00:01
   --------------------------------- ------ 13.4/15.8 MB 5.8 MB/s eta 0:00:01
   ---------------------------------- ----- 13.5/15.8 MB 5.7 MB/s eta 0:00:01
   ---------------------------------- ----- 13.6/15.8 MB 5.6 MB/s eta 0:00:01
   ---------------------------------- ----- 13.7/15.8 MB 5.5 MB/s eta 0:00:01
   ---------------------------------- ----- 13.8/15.8 MB 5.4 MB/s eta 0:00:01
   ----------------------------------- ---- 13.9/15.8 MB 5.4 MB/s eta 0:00:01
   ----------------------------------- ---- 14.1/15.8 MB 5.2 MB/s eta 0:00:01
   ----------------------------------- ---- 14.2/15.8 MB 5.2 MB/s eta 0:00:01
   ------------------------------------ --- 14.3/15.8 MB 5.1 MB/s eta 0:00:01
   ------------------------------------ --- 14.5/15.8 MB 5.0 MB/s eta 0:00:01
   ------------------------------------- -- 14.6/15.8 MB 5.0 MB/s eta 0:00:01
   ------------------------------------- -- 14.8/15.8 MB 5.0 MB/s eta 0:00:01
   ------------------------------------- -- 15.0/15.8 MB 4.8 MB/s eta 0:00:01
   -------------------------------------- - 15.3/15.8 MB 4.8 MB/s eta 0:00:01
   ---------------------------------------  15.6/15.8 MB 4.7 MB/s eta 0:00:01
   ---------------------------------------  15.8/15.8 MB 4.7 MB/s eta 0:00:01
   ---------------------------------------  15.8/15.8 MB 4.7 MB/s eta 0:00:01
   ---------------------------------------- 15.8/15.8 MB 4.5 MB/s eta 0:00:00
Installing collected packages: numpy, kagglesdk, kagglehub
  Attempting uninstall: numpy
    Found existing installation: numpy 2.4.3
    Uninstalling numpy-2.4.3:
      Successfully uninstalled numpy-2.4.3
Successfully installed kagglehub-1.0.2 kagglesdk-0.1.33 numpy-1.26.4

  WARNING: Failed to remove contents in a temporary directory 'C:\Users\famil\anaconda3\Lib\site-packages\~umpy.libs'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\famil\AppData\Local\Temp\pip-uninstall-ijpx_gfb'.
  You can safely remove it manually.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gensim 4.3.0 requires FuzzyTM>=0.4.0, which is not installed.
langchain 0.1.16 requires langchain-community<0.1,>=0.0.32, which is not installed.
gradio 6.0.1 requires pydantic<=2.12.4,>=2.11.10, but you have pydantic 2.12.5 which is incompatible.
opencv-python 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
streamlit 1.51.0 requires pyarrow<22,>=7.0, but you have pyarrow 23.0.1 which is incompatible.

In [2]:
import sys
print(sys.executable)

C:\Users\famil\anaconda3\python.exe

In [4]:
import kagglehub
import pandas as pd
print("All good, ready to go!")

All good, ready to go!

In [5]:
import kagglehub

# Download the full dataset (it's small - ~72MB total)
path = kagglehub.dataset_download("saurabhshahane/long-lived-bug-prediction")
print("Dataset downloaded to:", path)

Downloading to C:\Users\famil\.cache\kagglehub\datasets\saurabhshahane\long-lived-bug-prediction\1.archive...

100%|█████████████████████████████████████████████████████████████████████████████| 20.8M/20.8M [00:04<00:00, 4.39MB/s]

Extracting files...

Dataset downloaded to: C:\Users\famil\.cache\kagglehub\datasets\saurabhshahane\long-lived-bug-prediction\versions\1

In [43]:
'''import pandas as pd
mozilla_df = pd.read_csv(".../AI_Smart_Bug_Analyzer_-_Fix-_Advisor-/data/mozilla_bug_report_data.csv/mozilla_bug_report_data.csv")
eclipse_df = pd.read_csv(".../AI_Smart_Bug_Analyzer_-_Fix-_Advisor-/data/eclipse_bug_report_data.csv/eclipse_bug_report_data.csv")
print(mozilla_df.shape)
print(eclipse_df.shape)

print(mozilla_df.head())

print( eclipse_df.head())'''




import pandas as pd
mozilla_df = pd.read_csv("C:/Users/famil/OneDrive/Desktop/AI_Smart_Bug_Analyzer_-_Fix-_Advisor-/data/mozilla_bug_report_data.csv/mozilla_bug_report_data.csv")
eclipse_df = pd.read_csv("C:/Users/famil/OneDrive/Desktop/AI_Smart_Bug_Analyzer_-_Fix-_Advisor-/data/eclipse_bug_report_data.csv/eclipse_bug_report_data.csv")
print(mozilla_df.shape)
print(eclipse_df.shape)

mozilla_df.head()

(9999, 19)
(9776, 19)

,bug_id,creation_date,component_name,product_name,short_description,long_description,assignee_name,reporter_name,resolution_category,resolution_code,status_category,status_code,update_date,quantity_of_votes,quantity_of_comments,resolution_date,bug_fix_time,severity_category,severity_code
0,BUGZILLA-294734,2005-05-18,Bugzilla-General,BUGZILLA,Emergency 2.16.10 Release,2.16.9 is broken -- many users can't enter bug...,mkanat,mkanat,fixed,1,resolved,4,2005-05-19,0,15,2005-05-19,1,blocker,6
1,OTHER_APPLICATIONS-363323,2006-12-09,DOM Inspector,OTHER_APPLICATIONS,DOM View is really inefficient with setting wh...,From comment in url:\n\nCurrent code:\nmenuite...,sdwilsh,sdwilsh,fixed,1,resolved,4,2011-06-01,0,8,2007-01-14,36,normal,2
2,SUPPORT.MOZILLA.ORG-398246,2007-10-02,General,SUPPORT.MOZILLA.ORG,Add support for custom cookies and cache headers,Adding support for custom headers and cookie n...,morgamic,morgamic,fixed,1,resolved,4,2009-11-02,0,23,2008-03-24,174,blocker,6
3,RELEASE_ENGINEERING-525991,2009-11-02,General,RELEASE_ENGINEERING,Create Major Update from 3.0.15 to 3.5.5,NaN,catlee,catlee,fixed,1,resolved,4,2013-08-12,0,7,2009-11-10,8,normal,2
4,OTHER_APPLICATIONS-318859,2005-12-02,ChatZilla,OTHER_APPLICATIONS,DCC functionality in ChatZilla isn't functional.,User-Agent: Mozilla/5.0 (Macintosh U PPC...,gijskruitbosch+bugs,dafydd,fixed,1,resolved,4,2006-02-10,0,14,2005-12-07,5,normal,2

In [44]:
apache_df = pd.read_csv(r"D:/issues.csv", nrows=10000)
print(apache_df.shape)
apache_df.head()

#apache_df.describe()

(10000, 37)

,id,key,summary,resolution.id,resolution.description,resolution.name,priority.id,priority.name,labels,assignee,...,project.key,project.name,projectCategory.id,projectCategory.description,projectCategory.name,resolutiondate,watches.watchCount,created,updated,description
0,12451174,WW-712,Update config browser to work with the new syntax,1.0,A fix for this issue is checked into the tree ...,Fixed,4.0,Minor,[],632ec9dd,...,WW,Struts 2,10380.0,struts.apache.org,Struts Framework,2005-01-01 07:50:46,0,2005-01-01 07:47:50,2005-01-01 07:50:46,The config browser used Velocity calling the t...
1,29159,XALANC-446,XALAN_C 1.9 or current do not build on Fedora ...,1.0,A fix for this issue is checked into the tree ...,Fixed,1.0,Blocker,[],NaN,...,XALANC,XalanC,11460.0,Xalan Related Projects,Xalan,2004-12-30 05:30:36,1,2004-12-25 22:50:30,2005-01-01 10:20:52,Two types of errors:\n1- runConfigure and conf...
2,12420130,ROL-587,"Problem with ADD new post, and DELETE post.",5.0,"All attempts at reproducing this issue failed,...",Cannot Reproduce,2.0,Critical,[],4d4054ac,...,ROL,Apache Roller,10331.0,NaN,Roller,2005-01-02 15:21:00,0,2005-01-01 13:52:46,2005-01-02 15:21:00,"When trying to add new post, I was getting nex..."
3,29222,AXIS-1741,LogHandler can only work in GlobalConfiguratio...,NaN,NaN,NaN,3.0,Major,[],NaN,...,AXIS,Axis,10401.0,Axis and Axis2 related projects,Axis,NaN,0,2005-01-02 19:13:37,2005-01-02 19:35:36,org.apache.axis.handlers.LogHandler in request...
4,29233,AXIS-1745,Decoding of service is broken in org.apache.ax...,NaN,NaN,NaN,3.0,Major,[],NaN,...,AXIS,Axis,10401.0,Axis and Axis2 related projects,Axis,NaN,1,2005-01-03 03:34:52,2005-01-03 03:34:52,The following code assumes a lot of things:\n\...

In [34]:
mozilla_df.columns
mozilla_df['status_category']

0       resolved
1       resolved
2       resolved
3       resolved
4       resolved
          ...
9994    resolved
9995    resolved
9996    resolved
9997    resolved
9998    resolved
Name: status_category, Length: 9999, dtype: object

In [42]:
print(mozilla_df.columns)
print(apache_df.columns)
apache_df[['resolution.id', 'resolution.description',
       'resolution.name','statusCategory.name']]

Index(['bug_id', 'creation_date', 'component_name', 'product_name',
       'short_description', 'long_description', 'assignee_name',
       'reporter_name', 'resolution_category', 'resolution_code',
       'status_category', 'status_code', 'update_date', 'quantity_of_votes',
       'quantity_of_comments', 'resolution_date', 'bug_fix_time',
       'severity_category', 'severity_code'],
      dtype='object')
Index(['id', 'key', 'summary', 'resolution.id', 'resolution.description',
       'resolution.name', 'priority.id', 'priority.name', 'labels', 'assignee',
       'status.id', 'status.description', 'status.name', 'statusCategory.id',
       'statusCategory.key', 'statusCategory.colorName', 'statusCategory.name',
       'customfield_12310921', 'creator', 'subtasks', 'reporter',
       'votes.votes', 'issuetype.id', 'issuetype.description',
       'issuetype.name', 'issuetype.subtask', 'project.id', 'project.key',
       'project.name', 'projectCategory.id', 'projectCategory.description',
       'projectCategory.name', 'resolutiondate', 'watches.watchCount',
       'created', 'updated', 'description'],
      dtype='object')

,resolution.id,resolution.description,resolution.name,statusCategory.name
0,1.0,A fix for this issue is checked into the tree ...,Fixed,Done
1,1.0,A fix for this issue is checked into the tree ...,Fixed,Done
2,5.0,"All attempts at reproducing this issue failed,...",Cannot Reproduce,Done
3,NaN,NaN,NaN,To Do
4,NaN,NaN,NaN,To Do
...,...,...,...,...
9995,1.0,A fix for this issue is checked into the tree ...,Fixed,Done
9996,3.0,The problem is a duplicate of an existing issue.,Duplicate,Done
9997,1.0,A fix for this issue is checked into the tree ...,Fixed,Done
9998,5.0,"All attempts at reproducing this issue failed,...",Cannot Reproduce,Done
9999,1.0,A fix for this issue is checked into the tree ...,Fixed,Done

In [40]:
mozilla_std = pd.DataFrame({
    'bug_id':mozilla_df['bug_id'],
    'title':mozilla_df['short_description'],
    'description':mozilla_df['long_description'],
    'severity':mozilla_df['severity_category'],
    'resolution':mozilla_df['resolution_category'],
    'status':mozilla_df['status_category'],
    'source_dataset':'Mozilla'
}
    
)

eclipse_std = pd.DataFrame({
    'bug_id':eclipse_df['bug_id'],
    'title':eclipse_df['short_description'],
    'description':eclipse_df['long_description'],
    'severity':eclipse_df ['severity_category'],
    'resolution':eclipse_df['resolution_category'],
    'status':eclipse_df['status_category'],
    'source_dataset':'Eclipse'
}
    
)

apache_std = pd.DataFrame({
    'bug_id':apache_df['key'],
    'title':apache_df['summary'],
    'description':apache_df['description'],
    'severity':apache_df ['priority.name'],
    'resolution':apache_df['resolution.name'],
    'status':apache_df['statusCategory.name'],
    'source_dataset':'Apache'
    
})

print('Mozilla:',mozilla_std.shape)
print('Eclipse:',eclipse_std.shape)
print('Apache:',apache_std.shape)

Mozilla: (9999, 7)
Eclipse: (9776, 7)
Apache: (10000, 7)

In [45]:
mozilla_std['stack_trace'] = None
eclipse_std['stack_trace'] = None
apache_std['stack_trace'] = None

mozilla_std['product_component'] = mozilla_df['product_name']
eclipse_std['product_component'] = eclipse_df['product_name']
apache_std['product_component'] = apache_df['project.name']


print(mozilla_std.shape)
print(eclipse_std.shape)
print(apache_std.shape)

mozilla_std.head()

(9999, 9)
(9776, 9)
(10000, 9)

,bug_id,title,description,severity,resolution,status,source_dataset,stack_trace,product_component
0,BUGZILLA-294734,Emergency 2.16.10 Release,2.16.9 is broken -- many users can't enter bug...,blocker,fixed,resolved,Mozilla,None,BUGZILLA
1,OTHER_APPLICATIONS-363323,DOM View is really inefficient with setting wh...,From comment in url:\n\nCurrent code:\nmenuite...,normal,fixed,resolved,Mozilla,None,OTHER_APPLICATIONS
2,SUPPORT.MOZILLA.ORG-398246,Add support for custom cookies and cache headers,Adding support for custom headers and cookie n...,blocker,fixed,resolved,Mozilla,None,SUPPORT.MOZILLA.ORG
3,RELEASE_ENGINEERING-525991,Create Major Update from 3.0.15 to 3.5.5,NaN,normal,fixed,resolved,Mozilla,None,RELEASE_ENGINEERING
4,OTHER_APPLICATIONS-318859,DCC functionality in ChatZilla isn't functional.,User-Agent: Mozilla/5.0 (Macintosh U PPC...,normal,fixed,resolved,Mozilla,None,OTHER_APPLICATIONS

In [47]:
knowledge_base_df = pd.concat([mozilla_std,eclipse_std,apache_std], ignore_index = True)
print("Comobo Size " , knowledge_base_df.shape)
knowledge_base_df['source_dataset'].value_counts()

Comobo Size  (29775, 9)

source_dataset
Apache     10000
Mozilla     9999
Eclipse     9776
Name: count, dtype: int64

In [60]:
knowledge_base_df.to_csv("C:/Users/famil/OneDrive/Desktop/AI_Smart_Bug_Analyzer_-_Fix-_Advisor-/data/knowledge_basic_combined.csv" , index = False)
print("Saved Sucessfully")

Saved Sucessfully

# TASK 7:DATA CLEANING

In [54]:
print(knowledge_base_df.isnull().sum())
print("\n\nDuplicate id : ",knowledge_base_df['bug_id'].duplicated().sum())
print("\n\nShape before cleaning : ",knowledge_base_df.shape)

bug_id                   0
title                    1
description            613
severity               354
resolution            1036
status                1036
source_dataset           0
stack_trace          29775
product_component        0
dtype: int64


Duplicate id :  0


Shape before cleaning :  (29775, 9)

In [57]:
knowledge_base_clean = knowledge_base_df.dropna(subset = ['title','description'])

knowledge_base_clean = knowledge_base_clean.fillna({
    'severity':'Unknown',
    'resolution':'Not Specificed',
    'status':'Unknown'
})

print("Shape after cleaning :",knowledge_base_clean.shape)
print("\nRemaining nulls : \n",knowledge_base_clean.isnull().sum())

Shape after cleaning : (29161, 9)

Remaining nulls :
 bug_id                   0
title                    0
description              0
severity                 0
resolution               0
status                   0
source_dataset           0
stack_trace          29161
product_component        0
dtype: int64

In [58]:
import re

def clean_text(text):
    if pd.isna(text):
        return(text)
    text =  str(text)
    text = re.sub(r'<[^>]+>',' ',text)
    text = re.sub(r'\s+',' ',text)
    return text.strip()

knowledge_base_clean['title'] = knowledge_base_clean['title'].apply(clean_text)
knowledge_base_clean['description'] = knowledge_base_clean['description'].apply(clean_text)

print('Cleaning applied . A Sample of that :')
knowledge_base_clean[['title','description']].head(3)

Cleaning applied . A Sample of that :

,title,description
0,Emergency 2.16.10 Release,2.16.9 is broken -- many users can't enter bug...
1,DOM View is really inefficient with setting wh...,From comment in url: Current code: menuitem ->...
2,Add support for custom cookies and cache headers,Adding support for custom headers and cookie n...

In [61]:
knowledge_base_clean.to_csv("C:/Users/famil/OneDrive/Desktop/AI_Smart_Bug_Analyzer_-_Fix-_Advisor-/data/knowledge_base_cleaned.csv" , index = False)
print("Saved Cleaned knowledge Base")

Saved Cleaned knowledge Base

# TASK 8:Chunking with  Langchain

In [62]:
import sys
!{sys.executable} -m pip install langchain langchain-text-splitters

Requirement already satisfied: langchain in c:\users\famil\anaconda3\lib\site-packages (0.1.16)
Requirement already satisfied: langchain-text-splitters in c:\users\famil\anaconda3\lib\site-packages (0.0.2)
Requirement already satisfied: PyYAML>=5.3 in c:\users\famil\anaconda3\lib\site-packages (from langchain) (6.0.1)
Requirement already satisfied: SQLAlchemy<3,>=1.4 in c:\users\famil\anaconda3\lib\site-packages (from langchain) (2.0.25)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in c:\users\famil\anaconda3\lib\site-packages (from langchain) (3.9.3)
Requirement already satisfied: dataclasses-json<0.7,>=0.5.7 in c:\users\famil\anaconda3\lib\site-packages (from langchain) (0.6.7)
Requirement already satisfied: jsonpatch<2.0,>=1.33 in c:\users\famil\anaconda3\lib\site-packages (from langchain) (1.33)
Collecting langchain-community<0.1,>=0.0.32 (from langchain)
  Using cached langchain_community-0.0.38-py3-none-any.whl.metadata (8.7 kB)
Requirement already satisfied: langchain-core<0.2.0,>=0.1.42 in c:\users\famil\anaconda3\lib\site-packages (from langchain) (0.1.53)
Requirement already satisfied: langsmith<0.2.0,>=0.1.17 in c:\users\famil\anaconda3\lib\site-packages (from langchain) (0.1.147)
Requirement already satisfied: numpy<2,>=1 in c:\users\famil\anaconda3\lib\site-packages (from langchain) (1.26.4)
Requirement already satisfied: pydantic<3,>=1 in c:\users\famil\anaconda3\lib\site-packages (from langchain) (2.12.5)
Requirement already satisfied: requests<3,>=2 in c:\users\famil\anaconda3\lib\site-packages (from langchain) (2.33.0)
Requirement already satisfied: tenacity<9.0.0,>=8.1.0 in c:\users\famil\anaconda3\lib\site-packages (from langchain) (8.5.0)
Requirement already satisfied: aiosignal>=1.1.2 in c:\users\famil\anaconda3\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain) (1.2.0)
Requirement already satisfied: attrs>=17.3.0 in c:\users\famil\anaconda3\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain) (23.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\famil\anaconda3\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain) (1.4.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\famil\anaconda3\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain) (6.0.4)
Requirement already satisfied: yarl<2.0,>=1.0 in c:\users\famil\anaconda3\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain) (1.9.3)
Requirement already satisfied: marshmallow<4.0.0,>=3.18.0 in c:\users\famil\anaconda3\lib\site-packages (from dataclasses-json<0.7,>=0.5.7->langchain) (3.26.2)
Requirement already satisfied: typing-inspect<1,>=0.4.0 in c:\users\famil\anaconda3\lib\site-packages (from dataclasses-json<0.7,>=0.5.7->langchain) (0.9.0)
Requirement already satisfied: jsonpointer>=1.9 in c:\users\famil\anaconda3\lib\site-packages (from jsonpatch<2.0,>=1.33->langchain) (2.1)
Requirement already satisfied: packaging<24.0,>=23.2 in c:\users\famil\anaconda3\lib\site-packages (from langchain-core<0.2.0,>=0.1.42->langchain) (23.2)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\famil\anaconda3\lib\site-packages (from langsmith<0.2.0,>=0.1.17->langchain) (0.28.1)
Requirement already satisfied: orjson<4.0.0,>=3.9.14 in c:\users\famil\anaconda3\lib\site-packages (from langsmith<0.2.0,>=0.1.17->langchain) (3.11.4)
Requirement already satisfied: requests-toolbelt<2.0.0,>=1.0.0 in c:\users\famil\anaconda3\lib\site-packages (from langsmith<0.2.0,>=0.1.17->langchain) (1.0.0)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\famil\anaconda3\lib\site-packages (from pydantic<3,>=1->langchain) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in c:\users\famil\anaconda3\lib\site-packages (from pydantic<3,>=1->langchain) (2.41.5)
Requirement already satisfied: typing-extensions>=4.14.1 in c:\users\famil\anaconda3\lib\site-packages (from pydantic<3,>=1->langchain) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\famil\anaconda3\lib\site-packages (from pydantic<3,>=1->langchain) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\famil\anaconda3\lib\site-packages (from requests<3,>=2->langchain) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\famil\anaconda3\lib\site-packages (from requests<3,>=2->langchain) (3.11)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\famil\anaconda3\lib\site-packages (from requests<3,>=2->langchain) (2.0.7)
Requirement already satisfied: certifi>=2023.5.7 in c:\users\famil\anaconda3\lib\site-packages (from requests<3,>=2->langchain) (2026.2.25)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\famil\anaconda3\lib\site-packages (from SQLAlchemy<3,>=1.4->langchain) (3.0.1)
Requirement already satisfied: anyio in c:\users\famil\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->langsmith<0.2.0,>=0.1.17->langchain) (4.13.0)
Requirement already satisfied: httpcore==1.* in c:\users\famil\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->langsmith<0.2.0,>=0.1.17->langchain) (1.0.9)
Requirement already satisfied: h11>=0.16 in c:\users\famil\anaconda3\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->langsmith<0.2.0,>=0.1.17->langchain) (0.16.0)
Requirement already satisfied: mypy-extensions>=0.3.0 in c:\users\famil\anaconda3\lib\site-packages (from typing-inspect<1,>=0.4.0->dataclasses-json<0.7,>=0.5.7->langchain) (1.0.0)
Using cached langchain_community-0.0.38-py3-none-any.whl (2.0 MB)
Installing collected packages: langchain-community
Successfully installed langchain-community-0.0.38

In [67]:
from langchain_text_splitters import RecursiveCharacterTextSplitter

splitter = RecursiveCharacterTextSplitter(chunk_size=500 , chunk_overlap=50)

knowledge_base_clean['full_text'] = knowledge_base_clean['title'] + ". " + knowledge_base_clean['description']

sample_text = knowledge_base_clean['full_text'].iloc[0]
chunks = splitter.split_text(sample_text)

print("Original Text Length :",len(sample_text))
print("Numberof chunks :",len(chunks))
print("\nFirst Chunk:\n",chunks[0])

Original Text Length : 173
Numberof chunks : 1

First Chunk:
 Emergency 2.16.10 Release. 2.16.9 is broken -- many users can't enter bugs on it particularly not from a fresh install. So we need to pull 2.16.9 and post a 2.16.10 instead.

In [69]:
longer_text = knowledge_base_clean['full_text'].iloc[1]
chunks = splitter.split_text(longer_text)

print("Original Text Length :",len(longer_text))
print("Numberof chunks :",len(chunks))
print("\n--- Chunk 1 ---\n",chunks[0])
print("\n--- Chunk 2 ---\n",chunks[1] if len(chunks)>1 else "(only 1 chunk)")

Original Text Length : 304
Numberof chunks : 1

--- Chunk 1 ---
 DOM View is really inefficient with setting what is to be shown. From comment in url: Current code: menuitem -> command -> toggler -> setter -> pref -> observer -> setter -> pref Proposed code: menuitem -> command -> toggler -> pref -> observer -> setter arguably we should rebuild() in the observer too.

--- Chunk 2 ---
 (only 1 chunk)

In [72]:
longest_idx = knowledge_base_clean['full_text'].str.len().idxmax()
longest_text=knowledge_base_clean['full_text'].loc[longest_idx]

print("Length of longest text:", len(longest_text))  
chunks = splitter.split_text(longest_text)

print("Length of longest text:",len(chunks))
print("Number of chunks :",len(chunks))
print("\n--- Chunk 1 ---\n",chunks[0])
print("\n--- Chunk 2 ---\n",chunks[1] if len(chunks)>1 else "(only 1 chunk)")

Length of longest text: 64610
Length of longest text: 171
Number of chunks : 171

--- Chunk 1 ---
 [FIX]I am a beginner from China, and i can't work jetspeed with db2,please help me,ok?. As followed is my db2 ddl and populate file contents. CREATE TABLE TURBINE_USER ( USER_ID INTEGER NOT NULL, LOGIN_NAME VARCHAR (32) NOT NULL, PASSWORD_VALUE VARCHAR (32) NOT NULL, FIRST_NAME VARCHAR (99) NOT NULL, LAST_NAME VARCHAR (99) NOT NULL, EMAIL VARCHAR (99), CONFIRM_VALUE VARCHAR (99), MODIFIED TIMESTAMP, CREATED TIMESTAMP, LAST_LOGIN TIMESTAMP, DISABLED VARCHAR (1), OBJECTDATA CLOB(16777215),

--- Chunk 2 ---
 DISABLED VARCHAR (1), OBJECTDATA CLOB(16777215), PASSWORD_CHANGED TIMESTAMP, UNIQUE (LOGIN_NAME) ); ALTER TABLE TURBINE_USER ADD PRIMARY KEY (USER_ID); CREATE TABLE TURBINE_ROLE ( ROLE_ID INTEGER NOT NULL, ROLE_NAME VARCHAR (99) NOT NULL, OBJECTDATA CLOB(16777215), UNIQUE (ROLE_NAME) ); ALTER TABLE TURBINE_ROLE ADD PRIMARY KEY (ROLE_ID); CREATE TABLE TURBINE_GROUP ( GROUP_ID INTEGER NOT NULL, GROUP_NAME VARCHAR (99) NOT NULL, OBJECTDATA CLOB(16777215), UNIQUE (GROUP_NAME) ); ALTER TABLE

In [73]:
# Cap any single text at 3000 characters before chunking (keeps outliers from exploding chunk count)
knowledge_base_clean['full_text'] = knowledge_base_clean['full_text'].str[:3000]

In [75]:
all_chunks = []

for idx , row  in knowledge_base_clean.iterrows():
    text_chunks = splitter.split_text(row['full_text'])
    for i , chunk in enumerate(text_chunks):
        all_chunks.append({
            'chunk_id':f"{row['bug_id']}_chunk{i}",
            'bug_id':row['bug_id'],
            'chunk_text':chunk,
            'title':row['title'],
            'severity':row['severity'],
            'resolution':row['resolution'],
            'status':row['status'],
            'source_dataset':row['source_dataset']
        })

chunks_df = pd.DataFrame(all_chunks)
print("Total chunks created:",chunks_df.shape[0])
print("From original rows:", knowledge_base_clean.shape[0])
chunks_df.head(55)

Total chunks created: 56862
From original rows: 29161

,chunk_id,bug_id,chunk_text,title,severity,resolution,status,source_dataset
0,BUGZILLA-294734_chunk0,BUGZILLA-294734,Emergency 2.16.10 Release. 2.16.9 is broken --...,Emergency 2.16.10 Release,blocker,fixed,resolved,Mozilla
1,OTHER_APPLICATIONS-363323_chunk0,OTHER_APPLICATIONS-363323,DOM View is really inefficient with setting wh...,DOM View is really inefficient with setting wh...,normal,fixed,resolved,Mozilla
2,SUPPORT.MOZILLA.ORG-398246_chunk0,SUPPORT.MOZILLA.ORG-398246,Add support for custom cookies and cache heade...,Add support for custom cookies and cache headers,blocker,fixed,resolved,Mozilla
3,SUPPORT.MOZILLA.ORG-398246_chunk1,SUPPORT.MOZILLA.ORG-398246,at re-implementing some session libs I have fr...,Add support for custom cookies and cache headers,blocker,fixed,resolved,Mozilla
4,OTHER_APPLICATIONS-318859_chunk0,OTHER_APPLICATIONS-318859,DCC functionality in ChatZilla isn't functiona...,DCC functionality in ChatZilla isn't functional.,normal,fixed,resolved,Mozilla
5,OTHER_APPLICATIONS-318859_chunk1,OTHER_APPLICATIONS-318859,DCC offers matched. [18:54:22] [INFO] You must...,DCC functionality in ChatZilla isn't functional.,normal,fixed,resolved,Mozilla
6,OTHER_APPLICATIONS-318859_chunk2,OTHER_APPLICATIONS-318859,(67.186.207.96:55938) [Cancel]. [19:05:06][DCC...,DCC functionality in ChatZilla isn't functional.,normal,fixed,resolved,Mozilla
7,OTHER_APPLICATIONS-318859_chunk3,OTHER_APPLICATIONS-318859,function. Actual Results: Note that the functi...,DCC functionality in ChatZilla isn't functional.,normal,fixed,resolved,Mozilla
8,DEVELOPER.MOZILLA.ORG-416840_chunk0,DEVELOPER.MOZILLA.ORG-416840,Fix and cruft. Since we removed the breadcrumb...,Fix and cruft,normal,fixed,resolved,Mozilla
9,MARKETPLACE_GRAVEYARD-977729_chunk0,MARKETPLACE_GRAVEYARD-977729,add a waffle to disable the theme queue. This ...,add a waffle to disable the theme queue,normal,fixed,resolved,Mozilla
10,THUNDERBIRD-339875_chunk0,THUNDERBIRD-339875,ship ga-IE for 1.5.0.5. the ga-IE locale for T...,ship ga-IE for 1.5.0.5,normal,fixed,resolved,Mozilla
11,FIREFOX-420556_chunk0,FIREFOX-420556,sidebarheader on GNOME has a transparent backg...,sidebarheader on GNOME has a transparent backg...,normal,fixed,resolved,Mozilla
12,FIREFOX-420556_chunk1,FIREFOX-420556,top and bottom borders and it's unclear why th...,sidebarheader on GNOME has a transparent backg...,normal,fixed,resolved,Mozilla
13,FIREFOX-420556_chunk2,FIREFOX-420556,border rules to be applied and I looked at thr...,sidebarheader on GNOME has a transparent backg...,normal,fixed,resolved,Mozilla
14,FIREFOX-420556_chunk3,FIREFOX-420556,top and bottom border rules. Here's a patch th...,sidebarheader on GNOME has a transparent backg...,normal,fixed,resolved,Mozilla
15,FIREFOX-420556_chunk4,FIREFOX-420556,in the sidebar itself (f.e. the Search label i...,sidebarheader on GNOME has a transparent backg...,normal,fixed,resolved,Mozilla
16,MOZILLA_LOCALIZATIONS-415621_chunk0,MOZILLA_LOCALIZATIONS-415621,Firefox 3 mk release tracker. This is a tracke...,Firefox 3 mk release tracker,normal,fixed,resolved,Mozilla
17,CORE-254510_chunk0,CORE-254510,Bug 200433 regressed by patch in bug 253597. T...,Bug 200433 regressed by patch in bug 253597,major,fixed,resolved,Mozilla
18,CORE-204573_chunk0,CORE-204573,View-source highlighting is incorrect for XML ...,View-source highlighting is incorrect for XML ...,normal,fixed,resolved,Mozilla
19,CORE-204573_chunk1,CORE-204573,in a tag name (e. g. the attached file). Actua...,View-source highlighting is incorrect for XML ...,normal,fixed,resolved,Mozilla
20,CORE-204573_chunk2,CORE-204573,and Mozilla 1.0 (PC/Linux) - In the case of an...,View-source highlighting is incorrect for XML ...,normal,fixed,resolved,Mozilla
21,THUNDERBIRD-412434_chunk0,THUNDERBIRD-412434,opening a window with -chrome does not work an...,opening a window with -chrome does not work an...,normal,fixed,resolved,Mozilla
22,THUNDERBIRD-412434_chunk1,THUNDERBIRD-412434,but that function is defined nowhere in the fi...,opening a window with -chrome does not work an...,normal,fixed,resolved,Mozilla
23,OTHER_APPLICATIONS_GRAVEYARD-391445_chunk0,OTHER_APPLICATIONS_GRAVEYARD-391445,Unsightly border around clicked tabs. With the...,Unsightly border around clicked tabs,normal,fixed,resolved,Mozilla
24,FIREFOX_OS_GRAVEYARD-942470_chunk0,FIREFOX_OS_GRAVEYARD-942470,test_user_agent_updates.htmltest_user_agent_ov...,test_user_agent_updates.htmltest_user_agent_ov...,normal,fixed,resolved,Mozilla
25,FIREFOX_OS_GRAVEYARD-942470_chunk1,FIREFOX_OS_GRAVEYARD-942470,OS X 10.8) != -1 but intermittently instead of...,test_user_agent_updates.htmltest_user_agent_ov...,normal,fixed,resolved,Mozilla
26,TECH_EVANGELISM_GRAVEYARD-142958_chunk0,TECH_EVANGELISM_GRAVEYARD-142958,oracle.usu.ru - form is submitted incorrectly ...,oracle.usu.ru - form is submitted incorrectly ...,normal,fixed,resolved,Mozilla
27,TECH_EVANGELISM_GRAVEYARD-142958_chunk1,TECH_EVANGELISM_GRAVEYARD-142958,is only one text field (for entering the searc...,oracle.usu.ru - form is submitted incorrectly ...,normal,fixed,resolved,Mozilla
28,TECH_EVANGELISM_GRAVEYARD-142958_chunk2,TECH_EVANGELISM_GRAVEYARD-142958,it should looks like: 'XXX mathes found. Your ...,oracle.usu.ru - form is submitted incorrectly ...,normal,fixed,resolved,Mozilla
29,TECH_EVANGELISM_GRAVEYARD-142958_chunk3,TECH_EVANGELISM_GRAVEYARD-142958,has an OnClick event document.forms[0].submit(...,oracle.usu.ru - form is submitted incorrectly ...,normal,fixed,resolved,Mozilla
30,CORE-128371_chunk0,CORE-128371,menu items on the left side are not displayed....,menu items on the left side are not displayed,major,fixed,resolved,Mozilla
31,SEAMONKEY-160672_chunk0,SEAMONKEY-160672,[FIX]XP filepicker's modeGetFolder looks too m...,[FIX]XP filepicker's modeGetFolder looks too m...,normal,fixed,resolved,Mozilla
32,MOZILLA.ORG_GRAVEYARD-471000_chunk0,MOZILLA.ORG_GRAVEYARD-471000,qm-plinux-trunk04 needs a kick.. Currently unr...,qm-plinux-trunk04 needs a kick.,normal,fixed,resolved,Mozilla
33,CORE-459938_chunk0,CORE-459938,Video has incorrect colours. The video in the ...,Video has incorrect colours,normal,fixed,resolved,Mozilla
34,SEAMONKEY-57480_chunk0,SEAMONKEY-57480,problem with getting back to Font size 100% af...,problem with getting back to Font size 100% af...,normal,fixed,resolved,Mozilla
35,BUGZILLA-58242_chunk0,BUGZILLA-58242,relogin.cgi fails to delete server's copy of t...,relogin.cgi fails to delete server's copy of t...,minor,fixed,resolved,Mozilla
36,BUGZILLA-58242_chunk1,BUGZILLA-58242,SendSQL(delete from logincookies where userid=...,relogin.cgi fails to delete server's copy of t...,minor,fixed,resolved,Mozilla
37,FIREFOX_BUILD_SYSTEM-454709_chunk0,FIREFOX_BUILD_SYSTEM-454709,WinCE Resource Compiling Needs Shunt Applicati...,WinCE Resource Compiling Needs Shunt Application,normal,fixed,resolved,Mozilla
38,OTHER_APPLICATIONS-315913_chunk0,OTHER_APPLICATIONS-315913,Replace RDF userlist with direct nsITreeView i...,Replace RDF userlist with direct nsITreeView i...,normal,fixed,resolved,Mozilla
39,OTHER_APPLICATIONS-315913_chunk1,OTHER_APPLICATIONS-315913,proposal is changing the tree from a content v...,Replace RDF userlist with direct nsITreeView i...,normal,fixed,resolved,Mozilla
40,OTHER_APPLICATIONS-315913_chunk2,OTHER_APPLICATIONS-315913,are therefore removed in setCurrentObject my_c...,Replace RDF userlist with direct nsITreeView i...,normal,fixed,resolved,Mozilla
41,OTHER_APPLICATIONS-315913_chunk3,OTHER_APPLICATIONS-315913,row as the builder view does not permit arbitr...,Replace RDF userlist with direct nsITreeView i...,normal,fixed,resolved,Mozilla
42,MOZILLA.ORG_GRAVEYARD-516424_chunk0,MOZILLA.ORG_GRAVEYARD-516424,MDC badly broken this morning. MDC appears to ...,MDC badly broken this morning,blocker,fixed,resolved,Mozilla
43,MOZILLA_LOCALIZATIONS-372935_chunk0,MOZILLA_LOCALIZATIONS-372935,[ro] migration wizard string change. We want t...,[ro] migration wizard string change,normal,fixed,resolved,Mozilla
44,MOZILLA_LOCALIZATIONS-372935_chunk1,MOZILLA_LOCALIZATIONS-372935,The corresponding patch is the en-US part in h...,[ro] migration wizard string change,normal,fixed,resolved,Mozilla
45,TECH_EVANGELISM_GRAVEYARD-79139_chunk0,TECH_EVANGELISM_GRAVEYARD-79139,Danawa Korea Strict mode page has extraneous -...,Danawa Korea Strict mode page has extraneous -...,normal,fixed,resolved,Mozilla
46,CORE-353334_chunk0,CORE-353334,[FIX]Permission denied error scripting SVG fro...,[FIX]Permission denied error scripting SVG fro...,normal,fixed,resolved,Mozilla
47,CORE-353334_chunk1,CORE-353334,URL-encoded SVG document. I then add the objec...,[FIX]Permission denied error scripting SVG fro...,normal,fixed,resolved,Mozilla
48,CORE-353334_chunk2,CORE-353334,I have yet to see the same error when the file...,[FIX]Permission denied error scripting SVG fro...,normal,fixed,resolved,Mozilla
49,MOZILLA.ORG-83075_chunk0,MOZILLA.ORG-83075,Quip List requested. Is there any list of curr...,Quip List requested,normal,fixed,resolved,Mozilla
50,CAMINO_GRAVEYARD-294848_chunk0,CAMINO_GRAVEYARD-294848,Can't override dialog warning of duplicate ssl...,Can't override dialog warning of duplicate ssl...,normal,fixed,resolved,Mozilla
51,CAMINO_GRAVEYARD-294848_chunk1,CAMINO_GRAVEYARD-294848,for all their routers. Camino gives an error w...,Can't override dialog warning of duplicate ssl...,normal,fixed,resolved,Mozilla
52,CAMINO_GRAVEYARD-294848_chunk2,CAMINO_GRAVEYARD-294848,use a different browser. Firefox gives a simil...,Can't override dialog warning of duplicate ssl...,normal,fixed,resolved,Mozilla
53,CAMINO_GRAVEYARD-294848_chunk3,CAMINO_GRAVEYARD-294848,the router. Expected Results: Allow the user t...,Can't override dialog warning of duplicate ssl...,normal,fixed,resolved,Mozilla
54,INFRASTRUCTURE_&_OPERATIONS-848951_chunk0,INFRASTRUCTURE_&_OPERATIONS-848951,remove network block for the following hosts i...,remove network block for the following hosts i...,normal,fixed,resolved,Mozilla

In [76]:
chunks_df.to_csv("C:/Users/famil/OneDrive/Desktop/AI_Smart_Bug_Analyzer_-_Fix-_Advisor-/data/chunks_df.csv",index=False)
print("Saved Chunks")

Saved Chunks

# Task 9:Embedding

In [3]:
#!pip install pandas
import pandas as pd

# Reload your progress instead of redoing Tasks 6-8
knowledge_base_clean = pd.read_csv("C:/Users/famil/OneDrive/Desktop/AI_Smart_Bug_Analyzer_-_Fix-_Advisor-/data/knowledge_base_cleaned.csv")
chunks_df = pd.read_csv("C:/Users/famil/OneDrive/Desktop/AI_Smart_Bug_Analyzer_-_Fix-_Advisor-/data/chunks_df.csv")

print("Knowledge base reloaded:", knowledge_base_clean.shape)
print("Chunks reloaded:", chunks_df.shape)

Knowledge base reloaded: (29161, 9)
Chunks reloaded: (56862, 8)

In [2]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer('all-MiniLM-L6-v2')

print("Model loaded successfully")
print("Embedding dimension:", model.get_sentence_embedding_dimension())

[transformers] Disabling PyTorch because PyTorch >= 2.4 is required but found 2.2.2+cpu
[transformers] PyTorch was not found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
[transformers] PyTorch was not found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.

NameError: name 'nn' is not defined

In [77]:
import sys
!{sys.executable} -m pip install sentence-transformers

Collecting sentence-transformers
  Downloading sentence_transformers-5.6.0-py3-none-any.whl.metadata (18 kB)
Collecting transformers<6.0.0,>=4.41.0 (from sentence-transformers)
  Downloading transformers-5.13.0-py3-none-any.whl.metadata (32 kB)
Requirement already satisfied: huggingface-hub>=0.23.0 in c:\users\famil\anaconda3\lib\site-packages (from sentence-transformers) (1.1.6)
Collecting torch>=1.11.0 (from sentence-transformers)
  Downloading torch-2.13.0-cp311-cp311-win_amd64.whl.metadata (39 kB)
Requirement already satisfied: numpy>=1.20.0 in c:\users\famil\anaconda3\lib\site-packages (from sentence-transformers) (1.26.4)
Requirement already satisfied: scikit-learn>=0.22.0 in c:\users\famil\anaconda3\lib\site-packages (from sentence-transformers) (1.2.2)
Requirement already satisfied: scipy>=1.0.0 in c:\users\famil\anaconda3\lib\site-packages (from sentence-transformers) (1.11.4)
Requirement already satisfied: typing_extensions>=4.5.0 in c:\users\famil\anaconda3\lib\site-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: tqdm>=4.0.0 in c:\users\famil\anaconda3\lib\site-packages (from sentence-transformers) (4.67.3)
Requirement already satisfied: filelock in c:\users\famil\anaconda3\lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (3.13.1)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\famil\anaconda3\lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (2023.10.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in c:\users\famil\anaconda3\lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (1.2.0)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\famil\anaconda3\lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.28.1)
Requirement already satisfied: packaging>=20.9 in c:\users\famil\anaconda3\lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (23.2)
Requirement already satisfied: pyyaml>=5.1 in c:\users\famil\anaconda3\lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (6.0.1)
Requirement already satisfied: shellingham in c:\users\famil\anaconda3\lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (1.5.4)
Requirement already satisfied: typer-slim in c:\users\famil\anaconda3\lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.20.0)
Requirement already satisfied: joblib>=1.1.1 in c:\users\famil\anaconda3\lib\site-packages (from scikit-learn>=0.22.0->sentence-transformers) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\famil\anaconda3\lib\site-packages (from scikit-learn>=0.22.0->sentence-transformers) (2.2.0)
Collecting setuptools>=77.0.3 (from torch>=1.11.0->sentence-transformers)
  Downloading setuptools-83.0.0-py3-none-any.whl.metadata (6.6 kB)
Collecting sympy>=1.13.3 (from torch>=1.11.0->sentence-transformers)
  Using cached sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: networkx>=2.5.1 in c:\users\famil\anaconda3\lib\site-packages (from torch>=1.11.0->sentence-transformers) (3.1)
Requirement already satisfied: jinja2 in c:\users\famil\anaconda3\lib\site-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: colorama in c:\users\famil\anaconda3\lib\site-packages (from tqdm>=4.0.0->sentence-transformers) (0.4.6)
Collecting huggingface-hub>=0.23.0 (from sentence-transformers)
  Downloading huggingface_hub-1.22.0-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: regex>=2025.10.22 in c:\users\famil\anaconda3\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2026.1.15)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in c:\users\famil\anaconda3\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.22.2)
Requirement already satisfied: typer in c:\users\famil\anaconda3\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.20.0)
Collecting safetensors>=0.8.0 (from transformers<6.0.0,>=4.41.0->sentence-transformers)
  Downloading safetensors-0.8.0-cp310-abi3-win_amd64.whl.metadata (4.2 kB)
Collecting click<9.0.0,>=8.4.2 (from huggingface-hub>=0.23.0->sentence-transformers)
  Downloading click-8.4.2-py3-none-any.whl.metadata (2.6 kB)
Collecting hf-xet<2.0.0,>=1.5.1 (from huggingface-hub>=0.23.0->sentence-transformers)
  Downloading hf_xet-1.5.1-cp37-abi3-win_amd64.whl.metadata (4.9 kB)
Requirement already satisfied: anyio in c:\users\famil\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (4.13.0)
Requirement already satisfied: certifi in c:\users\famil\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (2026.2.25)
Requirement already satisfied: httpcore==1.* in c:\users\famil\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in c:\users\famil\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (3.11)
Requirement already satisfied: h11>=0.16 in c:\users\famil\anaconda3\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\famil\anaconda3\lib\site-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\famil\anaconda3\lib\site-packages (from jinja2->torch>=1.11.0->sentence-transformers) (2.1.3)
Requirement already satisfied: rich>=10.11.0 in c:\users\famil\anaconda3\lib\site-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (13.9.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\famil\anaconda3\lib\site-packages (from rich>=10.11.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\famil\anaconda3\lib\site-packages (from rich>=10.11.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\famil\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (0.1.0)
Downloading sentence_transformers-5.6.0-py3-none-any.whl (596 kB)
   ---------------------------------------- 0.0/596.4 kB ? eta -:--:--
   ----------------- ---------------------- 256.0/596.4 kB 7.7 MB/s eta 0:00:01
   --------------------------------- ------ 501.8/596.4 kB 6.3 MB/s eta 0:00:01
   ---------------------------------------- 596.4/596.4 kB 4.7 MB/s eta 0:00:00
Downloading torch-2.13.0-cp311-cp311-win_amd64.whl (122.0 MB)
   ---------------------------------------- 0.0/122.0 MB ? eta -:--:--
   ---------------------------------------- 0.2/122.0 MB 6.9 MB/s eta 0:00:18
   ---------------------------------------- 0.4/122.0 MB 6.3 MB/s eta 0:00:20
   ---------------------------------------- 0.7/122.0 MB 6.6 MB/s eta 0:00:19
   ---------------------------------------- 0.9/122.0 MB 6.3 MB/s eta 0:00:20
   ---------------------------------------- 1.1/122.0 MB 5.6 MB/s eta 0:00:22
   ---------------------------------------- 1.3/122.0 MB 5.5 MB/s eta 0:00:23
   ---------------------------------------- 1.4/122.0 MB 5.2 MB/s eta 0:00:24
   ---------------------------------------- 1.5/122.0 MB 5.1 MB/s eta 0:00:24
    --------------------------------------- 1.6/122.0 MB 4.4 MB/s eta 0:00:28
    --------------------------------------- 1.7/122.0 MB 4.1 MB/s eta 0:00:30
    --------------------------------------- 1.8/122.0 MB 3.9 MB/s eta 0:00:32
    --------------------------------------- 2.0/122.0 MB 4.1 MB/s eta 0:00:29
    --------------------------------------- 2.2/122.0 MB 4.2 MB/s eta 0:00:29
    --------------------------------------- 2.4/122.0 MB 4.1 MB/s eta 0:00:30
    --------------------------------------- 2.7/122.0 MB 4.4 MB/s eta 0:00:28
    --------------------------------------- 3.0/122.0 MB 4.5 MB/s eta 0:00:27
   - -------------------------------------- 3.2/122.0 MB 4.5 MB/s eta 0:00:27
   - -------------------------------------- 3.6/122.0 MB 4.7 MB/s eta 0:00:26
   - -------------------------------------- 4.0/122.0 MB 4.9 MB/s eta 0:00:25
   - -------------------------------------- 4.3/122.0 MB 5.1 MB/s eta 0:00:24
   - -------------------------------------- 4.5/122.0 MB 5.1 MB/s eta 0:00:24
   - -------------------------------------- 4.7/122.0 MB 5.0 MB/s eta 0:00:24
   - -------------------------------------- 4.9/122.0 MB 5.0 MB/s eta 0:00:24
   - -------------------------------------- 5.1/122.0 MB 5.0 MB/s eta 0:00:24
   - -------------------------------------- 5.4/122.0 MB 5.0 MB/s eta 0:00:24
   - -------------------------------------- 5.5/122.0 MB 4.9 MB/s eta 0:00:24
   - -------------------------------------- 5.8/122.0 MB 5.0 MB/s eta 0:00:24
   - -------------------------------------- 5.9/122.0 MB 5.0 MB/s eta 0:00:24
   - -------------------------------------- 6.0/122.0 MB 4.9 MB/s eta 0:00:24
   -- ------------------------------------- 6.2/122.0 MB 4.9 MB/s eta 0:00:24
   -- ------------------------------------- 6.4/122.0 MB 4.9 MB/s eta 0:00:24
   -- ------------------------------------- 6.6/122.0 MB 4.8 MB/s eta 0:00:24
   -- ------------------------------------- 6.7/122.0 MB 4.7 MB/s eta 0:00:25
   -- ------------------------------------- 6.8/122.0 MB 4.7 MB/s eta 0:00:25
   -- ------------------------------------- 6.9/122.0 MB 4.7 MB/s eta 0:00:25
   -- ------------------------------------- 6.9/122.0 MB 4.7 MB/s eta 0:00:25
   -- ------------------------------------- 7.1/122.0 MB 4.5 MB/s eta 0:00:26
   -- ------------------------------------- 7.3/122.0 MB 4.5 MB/s eta 0:00:26
   -- ------------------------------------- 7.4/122.0 MB 4.5 MB/s eta 0:00:26
   -- ------------------------------------- 7.6/122.0 MB 4.4 MB/s eta 0:00:26
   -- ------------------------------------- 7.7/122.0 MB 4.4 MB/s eta 0:00:26
   -- ------------------------------------- 7.9/122.0 MB 4.4 MB/s eta 0:00:26
   -- ------------------------------------- 8.0/122.0 MB 4.4 MB/s eta 0:00:26
   -- ------------------------------------- 8.1/122.0 MB 4.3 MB/s eta 0:00:27
   -- ------------------------------------- 8.2/122.0 MB 4.3 MB/s eta 0:00:27
   -- ------------------------------------- 8.4/122.0 MB 4.3 MB/s eta 0:00:27
   -- ------------------------------------- 8.6/122.0 MB 4.3 MB/s eta 0:00:27
   -- ------------------------------------- 8.8/122.0 MB 4.2 MB/s eta 0:00:27
   -- ------------------------------------- 8.9/122.0 MB 4.2 MB/s eta 0:00:27
   -- ------------------------------------- 9.1/122.0 MB 4.2 MB/s eta 0:00:27
   --- ------------------------------------ 9.2/122.0 MB 4.2 MB/s eta 0:00:27
   --- ------------------------------------ 9.3/122.0 MB 4.1 MB/s eta 0:00:28
   --- ------------------------------------ 9.5/122.0 MB 4.1 MB/s eta 0:00:28
   --- ------------------------------------ 9.6/122.0 MB 4.1 MB/s eta 0:00:28
   --- ------------------------------------ 9.7/122.0 MB 4.1 MB/s eta 0:00:28
   --- ------------------------------------ 9.9/122.0 MB 4.1 MB/s eta 0:00:28
   --- ------------------------------------ 10.1/122.0 MB 4.1 MB/s eta 0:00:28
   --- ------------------------------------ 10.2/122.0 MB 4.1 MB/s eta 0:00:28
   --- ------------------------------------ 10.4/122.0 MB 4.0 MB/s eta 0:00:28
   --- ------------------------------------ 10.4/122.0 MB 4.0 MB/s eta 0:00:28
   --- ------------------------------------ 10.6/122.0 MB 4.0 MB/s eta 0:00:29
   --- ------------------------------------ 10.6/122.0 MB 3.9 MB/s eta 0:00:29
   --- ------------------------------------ 10.6/122.0 MB 3.9 MB/s eta 0:00:29
   --- ------------------------------------ 10.7/122.0 MB 3.8 MB/s eta 0:00:30
   --- ------------------------------------ 10.9/122.0 MB 3.8 MB/s eta 0:00:30
   --- ------------------------------------ 11.2/122.0 MB 3.8 MB/s eta 0:00:30
   --- ------------------------------------ 11.3/122.0 MB 3.8 MB/s eta 0:00:30
   --- ------------------------------------ 11.5/122.0 MB 3.8 MB/s eta 0:00:30
   --- ------------------------------------ 11.7/122.0 MB 3.8 MB/s eta 0:00:30
   --- ------------------------------------ 11.9/122.0 MB 3.9 MB/s eta 0:00:29
   --- ------------------------------------ 12.1/122.0 MB 3.9 MB/s eta 0:00:29
   ---- ----------------------------------- 12.2/122.0 MB 3.9 MB/s eta 0:00:29
   ---- ----------------------------------- 12.4/122.0 MB 3.9 MB/s eta 0:00:29
   ---- ----------------------------------- 12.7/122.0 MB 3.9 MB/s eta 0:00:28
   ---- ----------------------------------- 12.9/122.0 MB 3.9 MB/s eta 0:00:29
   ---- ----------------------------------- 13.0/122.0 MB 3.9 MB/s eta 0:00:29
   ---- ----------------------------------- 13.2/122.0 MB 3.9 MB/s eta 0:00:29
   ---- ----------------------------------- 13.4/122.0 MB 3.9 MB/s eta 0:00:29
   ---- ----------------------------------- 13.5/122.0 MB 3.8 MB/s eta 0:00:29
   ---- ----------------------------------- 13.7/122.0 MB 3.8 MB/s eta 0:00:29
   ---- ----------------------------------- 13.8/122.0 MB 3.7 MB/s eta 0:00:29
   ---- ----------------------------------- 13.9/122.0 MB 3.7 MB/s eta 0:00:30
   ---- ----------------------------------- 14.1/122.0 MB 3.7 MB/s eta 0:00:30
   ---- ----------------------------------- 14.2/122.0 MB 3.7 MB/s eta 0:00:30
   ---- ----------------------------------- 14.4/122.0 MB 3.6 MB/s eta 0:00:30
   ---- ----------------------------------- 14.6/122.0 MB 3.6 MB/s eta 0:00:30
   ---- ----------------------------------- 14.8/122.0 MB 3.6 MB/s eta 0:00:30
   ---- ----------------------------------- 15.0/122.0 MB 3.6 MB/s eta 0:00:30
   ---- ----------------------------------- 15.1/122.0 MB 3.6 MB/s eta 0:00:31
   ----- ---------------------------------- 15.3/122.0 MB 3.6 MB/s eta 0:00:30
   ----- ---------------------------------- 15.4/122.0 MB 3.6 MB/s eta 0:00:30
   ----- ---------------------------------- 15.6/122.0 MB 3.5 MB/s eta 0:00:31
   ----- ---------------------------------- 15.7/122.0 MB 3.5 MB/s eta 0:00:31
   ----- ---------------------------------- 15.7/122.0 MB 3.5 MB/s eta 0:00:31
   ----- ---------------------------------- 15.8/122.0 MB 3.4 MB/s eta 0:00:31
   ----- ---------------------------------- 16.0/122.0 MB 3.4 MB/s eta 0:00:32
   ----- ---------------------------------- 16.0/122.0 MB 3.4 MB/s eta 0:00:32
   ----- ---------------------------------- 16.1/122.0 MB 3.4 MB/s eta 0:00:32
   ----- ---------------------------------- 16.1/122.0 MB 3.3 MB/s eta 0:00:32
   ----- ---------------------------------- 16.3/122.0 MB 3.3 MB/s eta 0:00:32
   ----- ---------------------------------- 16.5/122.0 MB 3.3 MB/s eta 0:00:32
   ----- ---------------------------------- 16.7/122.0 MB 3.3 MB/s eta 0:00:32
   ----- ---------------------------------- 16.9/122.0 MB 3.3 MB/s eta 0:00:32
   ----- ---------------------------------- 17.1/122.0 MB 3.4 MB/s eta 0:00:32
   ----- ---------------------------------- 17.4/122.0 MB 3.4 MB/s eta 0:00:31
   ----- ---------------------------------- 17.5/122.0 MB 3.4 MB/s eta 0:00:31
   ----- ---------------------------------- 17.7/122.0 MB 3.4 MB/s eta 0:00:31
   ----- ---------------------------------- 17.9/122.0 MB 3.5 MB/s eta 0:00:31
   ----- ---------------------------------- 18.1/122.0 MB 3.5 MB/s eta 0:00:30
   ------ --------------------------------- 18.3/122.0 MB 3.5 MB/s eta 0:00:30
   ------ --------------------------------- 18.5/122.0 MB 3.5 MB/s eta 0:00:30
   ------ --------------------------------- 18.7/122.0 MB 3.5 MB/s eta 0:00:30
   ------ --------------------------------- 18.9/122.0 MB 3.5 MB/s eta 0:00:30
   ------ --------------------------------- 19.1/122.0 MB 3.6 MB/s eta 0:00:29
   ------ --------------------------------- 19.4/122.0 MB 3.6 MB/s eta 0:00:29
   ------ --------------------------------- 19.5/122.0 MB 3.6 MB/s eta 0:00:29
   ------ --------------------------------- 19.7/122.0 MB 3.6 MB/s eta 0:00:29
   ------ --------------------------------- 19.9/122.0 MB 3.7 MB/s eta 0:00:28
   ------ --------------------------------- 20.2/122.0 MB 3.7 MB/s eta 0:00:28
   ------ --------------------------------- 20.4/122.0 MB 3.7 MB/s eta 0:00:28
   ------ --------------------------------- 20.6/122.0 MB 3.7 MB/s eta 0:00:28
   ------ --------------------------------- 20.8/122.0 MB 3.9 MB/s eta 0:00:26
   ------ --------------------------------- 21.0/122.0 MB 4.0 MB/s eta 0:00:26
   ------ --------------------------------- 21.3/122.0 MB 4.0 MB/s eta 0:00:26
   ------- -------------------------------- 21.4/122.0 MB 4.0 MB/s eta 0:00:26
   ------- -------------------------------- 21.4/122.0 MB 4.0 MB/s eta 0:00:26
   ------- -------------------------------- 21.4/122.0 MB 4.0 MB/s eta 0:00:26
   ------- -------------------------------- 21.4/122.0 MB 4.0 MB/s eta 0:00:26
   ------- -------------------------------- 21.4/122.0 MB 4.0 MB/s eta 0:00:26
   ------- -------------------------------- 21.7/122.0 MB 3.8 MB/s eta 0:00:27
   ------- -------------------------------- 21.7/122.0 MB 3.8 MB/s eta 0:00:27
   ------- -------------------------------- 21.7/122.0 MB 3.8 MB/s eta 0:00:27
   ------- -------------------------------- 21.7/122.0 MB 3.8 MB/s eta 0:00:27
   ------- -------------------------------- 21.9/122.0 MB 3.6 MB/s eta 0:00:29
   ------- -------------------------------- 21.9/122.0 MB 3.6 MB/s eta 0:00:29
   ------- -------------------------------- 21.9/122.0 MB 3.6 MB/s eta 0:00:29
   ------- -------------------------------- 21.9/122.0 MB 3.6 MB/s eta 0:00:29
   ------- -------------------------------- 22.1/122.0 MB 3.4 MB/s eta 0:00:30
   ------- -------------------------------- 22.1/122.0 MB 3.4 MB/s eta 0:00:30
   ------- -------------------------------- 22.1/122.0 MB 3.4 MB/s eta 0:00:30
   ------- -------------------------------- 22.1/122.0 MB 3.4 MB/s eta 0:00:30
   ------- -------------------------------- 22.1/122.0 MB 3.4 MB/s eta 0:00:30
   ------- -------------------------------- 22.3/122.0 MB 3.2 MB/s eta 0:00:31
   ------- -------------------------------- 22.3/122.0 MB 3.2 MB/s eta 0:00:31
   ------- -------------------------------- 22.3/122.0 MB 3.2 MB/s eta 0:00:31
   ------- -------------------------------- 22.3/122.0 MB 3.2 MB/s eta 0:00:31
   ------- -------------------------------- 22.4/122.0 MB 3.1 MB/s eta 0:00:33
   ------- -------------------------------- 22.4/122.0 MB 3.1 MB/s eta 0:00:33
   ------- -------------------------------- 22.4/122.0 MB 3.1 MB/s eta 0:00:33
   ------- -------------------------------- 22.4/122.0 MB 3.1 MB/s eta 0:00:33
   ------- -------------------------------- 22.5/122.0 MB 2.9 MB/s eta 0:00:34
   ------- -------------------------------- 22.6/122.0 MB 2.9 MB/s eta 0:00:35
   ------- -------------------------------- 22.6/122.0 MB 2.9 MB/s eta 0:00:35
   ------- -------------------------------- 22.6/122.0 MB 2.9 MB/s eta 0:00:35
   ------- -------------------------------- 22.6/122.0 MB 2.9 MB/s eta 0:00:35
   ------- -------------------------------- 22.6/122.0 MB 2.8 MB/s eta 0:00:36
   ------- -------------------------------- 22.7/122.0 MB 2.8 MB/s eta 0:00:36
   ------- -------------------------------- 22.7/122.0 MB 2.8 MB/s eta 0:00:36
   ------- -------------------------------- 22.7/122.0 MB 2.8 MB/s eta 0:00:36
   ------- -------------------------------- 22.7/122.0 MB 2.7 MB/s eta 0:00:38
   ------- -------------------------------- 22.8/122.0 MB 2.7 MB/s eta 0:00:38
   ------- -------------------------------- 22.8/122.0 MB 2.7 MB/s eta 0:00:38
   ------- -------------------------------- 22.8/122.0 MB 2.7 MB/s eta 0:00:38
   ------- -------------------------------- 22.8/122.0 MB 2.7 MB/s eta 0:00:38
   ------- -------------------------------- 22.9/122.0 MB 2.5 MB/s eta 0:00:39
   ------- -------------------------------- 22.9/122.0 MB 2.5 MB/s eta 0:00:39

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
conda-repo-cli 1.0.75 requires requests_mock, which is not installed.
conda-repo-cli 1.0.75 requires clyent==1.2.1, but you have clyent 1.2.2 which is incompatible.
conda-repo-cli 1.0.75 requires requests==2.31.0, but you have requests 2.33.0 which is incompatible.
gradio 6.0.1 requires pydantic<=2.12.4,>=2.11.10, but you have pydantic 2.12.5 which is incompatible.
streamlit 1.51.0 requires pyarrow<22,>=7.0, but you have pyarrow 23.0.1 which is incompatible.

   ------- -------------------------------- 24.2/122.0 MB 1.1 MB/s eta 0:01:30
   ------- -------------------------------- 24.2/122.0 MB 1.1 MB/s eta 0:01:30
   ------- -------------------------------- 24.2/122.0 MB 1.1 MB/s eta 0:01:31
   ------- -------------------------------- 24.3/122.0 MB 1.1 MB/s eta 0:01:31
   -------- ------------------------------- 24.5/122.0 MB 1.1 MB/s eta 0:01:31
   -------- ------------------------------- 24.6/122.0 MB 1.1 MB/s eta 0:01:31
   -------- ------------------------------- 24.8/122.0 MB 1.1 MB/s eta 0:01:31
   -------- ------------------------------- 24.9/122.0 MB 1.1 MB/s eta 0:01:31
   -------- ------------------------------- 25.0/122.0 MB 1.1 MB/s eta 0:01:31
   -------- ------------------------------- 25.2/122.0 MB 1.1 MB/s eta 0:01:31
   -------- ------------------------------- 25.4/122.0 MB 1.1 MB/s eta 0:01:30
   -------- ------------------------------- 25.5/122.0 MB 1.1 MB/s eta 0:01:30
   -------- ------------------------------- 25.7/122.0 MB 1.1 MB/s eta 0:01:30
   -------- ------------------------------- 25.9/122.0 MB 1.1 MB/s eta 0:01:29
   -------- ------------------------------- 26.1/122.0 MB 1.1 MB/s eta 0:01:29
   -------- ------------------------------- 26.3/122.0 MB 1.1 MB/s eta 0:01:28
   -------- ------------------------------- 26.4/122.0 MB 1.1 MB/s eta 0:01:28
   -------- ------------------------------- 26.6/122.0 MB 1.1 MB/s eta 0:01:28
   -------- ------------------------------- 26.8/122.0 MB 1.1 MB/s eta 0:01:27
   -------- ------------------------------- 27.0/122.0 MB 1.1 MB/s eta 0:01:27
   -------- ------------------------------- 27.2/122.0 MB 1.1 MB/s eta 0:01:27
   -------- ------------------------------- 27.3/122.0 MB 1.1 MB/s eta 0:01:27
   --------- ------------------------------ 27.5/122.0 MB 1.1 MB/s eta 0:01:27
   --------- ------------------------------ 27.7/122.0 MB 1.1 MB/s eta 0:01:27
   --------- ------------------------------ 27.8/122.0 MB 1.1 MB/s eta 0:01:27
   --------- ------------------------------ 28.0/122.0 MB 1.1 MB/s eta 0:01:27
   --------- ------------------------------ 28.2/122.0 MB 1.1 MB/s eta 0:01:27
   --------- ------------------------------ 28.4/122.0 MB 1.1 MB/s eta 0:01:26
   --------- ------------------------------ 28.5/122.0 MB 1.1 MB/s eta 0:01:26
   --------- ------------------------------ 28.7/122.0 MB 1.1 MB/s eta 0:01:26
   --------- ------------------------------ 28.9/122.0 MB 1.1 MB/s eta 0:01:26
   --------- ------------------------------ 29.1/122.0 MB 1.1 MB/s eta 0:01:26
   --------- ------------------------------ 29.4/122.0 MB 1.1 MB/s eta 0:01:26
   --------- ------------------------------ 29.5/122.0 MB 1.1 MB/s eta 0:01:26
   --------- ------------------------------ 29.7/122.0 MB 1.1 MB/s eta 0:01:25
   --------- ------------------------------ 29.9/122.0 MB 1.1 MB/s eta 0:01:25
   --------- ------------------------------ 30.2/122.0 MB 1.1 MB/s eta 0:01:25
   ---------- ----------------------------- 30.6/122.0 MB 1.1 MB/s eta 0:01:24
   ---------- ----------------------------- 30.9/122.0 MB 1.1 MB/s eta 0:01:24
   ---------- ----------------------------- 31.3/122.0 MB 1.1 MB/s eta 0:01:23
   ---------- ----------------------------- 31.4/122.0 MB 1.1 MB/s eta 0:01:23
   ---------- ----------------------------- 31.7/122.0 MB 1.1 MB/s eta 0:01:21
   ---------- ----------------------------- 32.0/122.0 MB 1.1 MB/s eta 0:01:20
   ---------- ----------------------------- 32.3/122.0 MB 1.2 MB/s eta 0:01:18
   ---------- ----------------------------- 32.6/122.0 MB 1.2 MB/s eta 0:01:15
   ---------- ----------------------------- 32.8/122.0 MB 1.2 MB/s eta 0:01:13
   ---------- ----------------------------- 33.2/122.0 MB 1.3 MB/s eta 0:01:06
   ---------- ----------------------------- 33.4/122.0 MB 1.5 MB/s eta 0:01:00
   ----------- ---------------------------- 33.7/122.0 MB 1.8 MB/s eta 0:00:49
   ----------- ---------------------------- 34.0/122.0 MB 2.4 MB/s eta 0:00:38
   ----------- ---------------------------- 34.2/122.0 MB 3.1 MB/s eta 0:00:29
   ----------- ---------------------------- 34.4/122.0 MB 4.7 MB/s eta 0:00:19
   ----------- ---------------------------- 34.6/122.0 MB 4.8 MB/s eta 0:00:19
   ----------- ---------------------------- 34.9/122.0 MB 4.9 MB/s eta 0:00:18
   ----------- ---------------------------- 35.1/122.0 MB 5.0 MB/s eta 0:00:18
   ----------- ---------------------------- 35.3/122.0 MB 5.0 MB/s eta 0:00:18
   ----------- ---------------------------- 35.7/122.0 MB 5.1 MB/s eta 0:00:18
   ----------- ---------------------------- 36.0/122.0 MB 5.2 MB/s eta 0:00:17
   ----------- ---------------------------- 36.2/122.0 MB 5.2 MB/s eta 0:00:17
   ----------- ---------------------------- 36.4/122.0 MB 5.2 MB/s eta 0:00:17
   ------------ --------------------------- 36.7/122.0 MB 5.3 MB/s eta 0:00:17
   ------------ --------------------------- 37.0/122.0 MB 5.4 MB/s eta 0:00:16
   ------------ --------------------------- 37.2/122.0 MB 5.5 MB/s eta 0:00:16
   ------------ --------------------------- 37.4/122.0 MB 5.4 MB/s eta 0:00:16
   ------------ --------------------------- 37.6/122.0 MB 5.5 MB/s eta 0:00:16
   ------------ --------------------------- 37.9/122.0 MB 5.6 MB/s eta 0:00:16
   ------------ --------------------------- 38.1/122.0 MB 5.6 MB/s eta 0:00:15
   ------------ --------------------------- 38.3/122.0 MB 5.6 MB/s eta 0:00:15
   ------------ --------------------------- 38.5/122.0 MB 5.7 MB/s eta 0:00:15
   ------------ --------------------------- 38.8/122.0 MB 5.7 MB/s eta 0:00:15
   ------------ --------------------------- 39.1/122.0 MB 5.8 MB/s eta 0:00:15
   ------------ --------------------------- 39.3/122.0 MB 5.8 MB/s eta 0:00:15
   ------------- -------------------------- 39.7/122.0 MB 6.0 MB/s eta 0:00:14
   ------------- -------------------------- 39.9/122.0 MB 6.0 MB/s eta 0:00:14
   ------------- -------------------------- 40.1/122.0 MB 6.0 MB/s eta 0:00:14
   ------------- -------------------------- 40.3/122.0 MB 6.0 MB/s eta 0:00:14
   ------------- -------------------------- 40.5/122.0 MB 5.9 MB/s eta 0:00:14
   ------------- -------------------------- 40.8/122.0 MB 5.8 MB/s eta 0:00:14
   ------------- -------------------------- 41.0/122.0 MB 5.9 MB/s eta 0:00:14
   ------------- -------------------------- 41.3/122.0 MB 5.9 MB/s eta 0:00:14
   ------------- -------------------------- 41.5/122.0 MB 5.8 MB/s eta 0:00:14
   ------------- -------------------------- 41.8/122.0 MB 5.8 MB/s eta 0:00:14
   ------------- -------------------------- 42.0/122.0 MB 5.7 MB/s eta 0:00:14
   ------------- -------------------------- 42.2/122.0 MB 5.7 MB/s eta 0:00:15
   ------------- -------------------------- 42.3/122.0 MB 5.6 MB/s eta 0:00:15
   ------------- -------------------------- 42.5/122.0 MB 5.6 MB/s eta 0:00:15
   -------------- ------------------------- 42.7/122.0 MB 5.5 MB/s eta 0:00:15
   -------------- ------------------------- 42.9/122.0 MB 5.5 MB/s eta 0:00:15
   -------------- ------------------------- 43.1/122.0 MB 5.6 MB/s eta 0:00:15
   -------------- ------------------------- 43.4/122.0 MB 5.5 MB/s eta 0:00:15
   -------------- ------------------------- 43.6/122.0 MB 5.5 MB/s eta 0:00:15
   -------------- ------------------------- 43.8/122.0 MB 5.4 MB/s eta 0:00:15
   -------------- ------------------------- 44.1/122.0 MB 5.4 MB/s eta 0:00:15
   -------------- ------------------------- 44.4/122.0 MB 5.5 MB/s eta 0:00:15
   -------------- ------------------------- 44.6/122.0 MB 5.4 MB/s eta 0:00:15
   -------------- ------------------------- 44.8/122.0 MB 5.5 MB/s eta 0:00:15
   -------------- ------------------------- 45.0/122.0 MB 5.4 MB/s eta 0:00:15
   -------------- ------------------------- 45.2/122.0 MB 5.4 MB/s eta 0:00:15
   -------------- ------------------------- 45.5/122.0 MB 5.4 MB/s eta 0:00:15
   -------------- ------------------------- 45.7/122.0 MB 5.3 MB/s eta 0:00:15
   --------------- ------------------------ 46.0/122.0 MB 5.5 MB/s eta 0:00:14
   --------------- ------------------------ 46.3/122.0 MB 5.4 MB/s eta 0:00:15
   --------------- ------------------------ 46.5/122.0 MB 5.4 MB/s eta 0:00:14
   --------------- ------------------------ 46.7/122.0 MB 5.4 MB/s eta 0:00:14
   --------------- ------------------------ 46.8/122.0 MB 5.4 MB/s eta 0:00:15
   --------------- ------------------------ 47.0/122.0 MB 5.3 MB/s eta 0:00:15
   --------------- ------------------------ 47.2/122.0 MB 5.2 MB/s eta 0:00:15
   --------------- ------------------------ 47.5/122.0 MB 5.2 MB/s eta 0:00:15
   --------------- ------------------------ 47.6/122.0 MB 5.2 MB/s eta 0:00:15
   --------------- ------------------------ 47.8/122.0 MB 5.2 MB/s eta 0:00:15
   --------------- ------------------------ 47.9/122.0 MB 5.2 MB/s eta 0:00:15
   --------------- ------------------------ 48.1/122.0 MB 5.1 MB/s eta 0:00:15
   --------------- ------------------------ 48.2/122.0 MB 5.1 MB/s eta 0:00:15
   --------------- ------------------------ 48.5/122.0 MB 5.1 MB/s eta 0:00:15
   --------------- ------------------------ 48.7/122.0 MB 5.0 MB/s eta 0:00:15
   ---------------- ----------------------- 48.8/122.0 MB 5.0 MB/s eta 0:00:15
   ---------------- ----------------------- 49.0/122.0 MB 5.0 MB/s eta 0:00:15
   ---------------- ----------------------- 49.2/122.0 MB 5.0 MB/s eta 0:00:15
   ---------------- ----------------------- 49.3/122.0 MB 4.9 MB/s eta 0:00:15
   ---------------- ----------------------- 49.5/122.0 MB 4.9 MB/s eta 0:00:15
   ---------------- ----------------------- 49.7/122.0 MB 4.8 MB/s eta 0:00:16
   ---------------- ----------------------- 49.8/122.0 MB 4.8 MB/s eta 0:00:15
   ---------------- ----------------------- 50.1/122.0 MB 4.8 MB/s eta 0:00:15
   ---------------- ----------------------- 50.3/122.0 MB 4.8 MB/s eta 0:00:15
   ---------------- ----------------------- 50.5/122.0 MB 4.8 MB/s eta 0:00:15
   ---------------- ----------------------- 50.7/122.0 MB 4.8 MB/s eta 0:00:15
   ---------------- ----------------------- 50.9/122.0 MB 4.8 MB/s eta 0:00:15
   ---------------- ----------------------- 51.2/122.0 MB 4.8 MB/s eta 0:00:15
   ---------------- ----------------------- 51.4/122.0 MB 4.7 MB/s eta 0:00:15
   ---------------- ----------------------- 51.7/122.0 MB 4.8 MB/s eta 0:00:15
   ----------------- ---------------------- 52.0/122.0 MB 4.8 MB/s eta 0:00:15
   ----------------- ---------------------- 52.3/122.0 MB 4.8 MB/s eta 0:00:15
   ----------------- ---------------------- 52.5/122.0 MB 4.9 MB/s eta 0:00:15
   ----------------- ---------------------- 52.7/122.0 MB 4.9 MB/s eta 0:00:15
   ----------------- ---------------------- 52.9/122.0 MB 4.9 MB/s eta 0:00:15
   ----------------- ---------------------- 53.0/122.0 MB 4.9 MB/s eta 0:00:15
   ----------------- ---------------------- 53.2/122.0 MB 4.9 MB/s eta 0:00:15
   ----------------- ---------------------- 53.4/122.0 MB 4.8 MB/s eta 0:00:15
   ----------------- ---------------------- 53.5/122.0 MB 4.8 MB/s eta 0:00:15
   ----------------- ---------------------- 53.7/122.0 MB 4.8 MB/s eta 0:00:15
   ----------------- ---------------------- 53.9/122.0 MB 4.8 MB/s eta 0:00:15
   ----------------- ---------------------- 54.1/122.0 MB 4.7 MB/s eta 0:00:15
   ----------------- ---------------------- 54.4/122.0 MB 4.7 MB/s eta 0:00:15
   ----------------- ---------------------- 54.6/122.0 MB 4.7 MB/s eta 0:00:15
   ----------------- ---------------------- 54.8/122.0 MB 4.7 MB/s eta 0:00:15
   ------------------ --------------------- 55.1/122.0 MB 4.7 MB/s eta 0:00:15
   ------------------ --------------------- 55.4/122.0 MB 4.8 MB/s eta 0:00:14
   ------------------ --------------------- 55.6/122.0 MB 4.8 MB/s eta 0:00:14
   ------------------ --------------------- 55.8/122.0 MB 4.8 MB/s eta 0:00:14
   ------------------ --------------------- 56.1/122.0 MB 4.8 MB/s eta 0:00:14
   ------------------ --------------------- 56.3/122.0 MB 4.8 MB/s eta 0:00:14
   ------------------ --------------------- 56.5/122.0 MB 4.7 MB/s eta 0:00:14
   ------------------ --------------------- 56.7/122.0 MB 4.8 MB/s eta 0:00:14
   ------------------ --------------------- 56.9/122.0 MB 4.8 MB/s eta 0:00:14
   ------------------ --------------------- 57.1/122.0 MB 4.8 MB/s eta 0:00:14
   ------------------ --------------------- 57.2/122.0 MB 4.8 MB/s eta 0:00:14
   ------------------ --------------------- 57.4/122.0 MB 4.7 MB/s eta 0:00:14
   ------------------ --------------------- 57.7/122.0 MB 4.7 MB/s eta 0:00:14
   ------------------ --------------------- 57.8/122.0 MB 4.7 MB/s eta 0:00:14
   ------------------- -------------------- 58.1/122.0 MB 4.7 MB/s eta 0:00:14
   ------------------- -------------------- 58.2/122.0 MB 4.7 MB/s eta 0:00:14
   ------------------- -------------------- 58.4/122.0 MB 4.8 MB/s eta 0:00:14
   ------------------- -------------------- 58.5/122.0 MB 4.8 MB/s eta 0:00:14
   ------------------- -------------------- 58.7/122.0 MB 4.7 MB/s eta 0:00:14
   ------------------- -------------------- 58.9/122.0 MB 4.7 MB/s eta 0:00:14
   ------------------- -------------------- 59.1/122.0 MB 4.8 MB/s eta 0:00:14
   ------------------- -------------------- 59.3/122.0 MB 4.8 MB/s eta 0:00:14
   ------------------- -------------------- 59.6/122.0 MB 4.8 MB/s eta 0:00:13
   ------------------- -------------------- 59.8/122.0 MB 4.9 MB/s eta 0:00:13
   ------------------- -------------------- 60.0/122.0 MB 4.9 MB/s eta 0:00:13
   ------------------- -------------------- 60.2/122.0 MB 4.9 MB/s eta 0:00:13
   ------------------- -------------------- 60.4/122.0 MB 4.9 MB/s eta 0:00:13
   ------------------- -------------------- 60.7/122.0 MB 4.9 MB/s eta 0:00:13
   ------------------- -------------------- 60.9/122.0 MB 4.9 MB/s eta 0:00:13
   -------------------- ------------------- 61.2/122.0 MB 4.9 MB/s eta 0:00:13
   -------------------- ------------------- 61.4/122.0 MB 4.9 MB/s eta 0:00:13
   -------------------- ------------------- 61.7/122.0 MB 4.9 MB/s eta 0:00:13
   -------------------- ------------------- 61.9/122.0 MB 4.9 MB/s eta 0:00:13
   -------------------- ------------------- 62.2/122.0 MB 4.9 MB/s eta 0:00:13
   -------------------- ------------------- 62.3/122.0 MB 4.8 MB/s eta 0:00:13
   -------------------- ------------------- 62.5/122.0 MB 4.7 MB/s eta 0:00:13
   -------------------- ------------------- 62.6/122.0 MB 4.7 MB/s eta 0:00:13
   -------------------- ------------------- 62.7/122.0 MB 4.6 MB/s eta 0:00:13
   -------------------- ------------------- 62.8/122.0 MB 4.6 MB/s eta 0:00:13
   -------------------- ------------------- 63.0/122.0 MB 4.6 MB/s eta 0:00:13
   -------------------- ------------------- 63.2/122.0 MB 4.7 MB/s eta 0:00:13
   -------------------- ------------------- 63.5/122.0 MB 4.7 MB/s eta 0:00:13
   -------------------- ------------------- 63.8/122.0 MB 4.8 MB/s eta 0:00:13
   --------------------- ------------------ 64.1/122.0 MB 4.8 MB/s eta 0:00:13
   --------------------- ------------------ 64.3/122.0 MB 4.8 MB/s eta 0:00:12
   --------------------- ------------------ 64.6/122.0 MB 4.8 MB/s eta 0:00:12
   --------------------- ------------------ 64.9/122.0 MB 4.9 MB/s eta 0:00:12
   --------------------- ------------------ 65.2/122.0 MB 4.9 MB/s eta 0:00:12
   --------------------- ------------------ 65.4/122.0 MB 4.9 MB/s eta 0:00:12
   --------------------- ------------------ 65.7/122.0 MB 4.8 MB/s eta 0:00:12
   --------------------- ------------------ 66.0/122.0 MB 4.8 MB/s eta 0:00:12
   --------------------- ------------------ 66.3/122.0 MB 4.8 MB/s eta 0:00:12
   --------------------- ------------------ 66.6/122.0 MB 4.9 MB/s eta 0:00:12
   --------------------- ------------------ 66.9/122.0 MB 4.9 MB/s eta 0:00:12
   ---------------------- ----------------- 67.2/122.0 MB 5.0 MB/s eta 0:00:11
   ---------------------- ----------------- 67.5/122.0 MB 5.0 MB/s eta 0:00:11
   ---------------------- ----------------- 67.7/122.0 MB 5.0 MB/s eta 0:00:11
   ---------------------- ----------------- 67.9/122.0 MB 5.1 MB/s eta 0:00:11
   ---------------------- ----------------- 68.1/122.0 MB 5.1 MB/s eta 0:00:11
   ---------------------- ----------------- 68.3/122.0 MB 5.1 MB/s eta 0:00:11
   ---------------------- ----------------- 68.5/122.0 MB 5.1 MB/s eta 0:00:11
   ---------------------- ----------------- 68.6/122.0 MB 5.1 MB/s eta 0:00:11
   ---------------------- ----------------- 68.8/122.0 MB 5.1 MB/s eta 0:00:11
   ---------------------- ----------------- 68.9/122.0 MB 5.1 MB/s eta 0:00:11
   ---------------------- ----------------- 69.1/122.0 MB 5.0 MB/s eta 0:00:11
   ---------------------- ----------------- 69.2/122.0 MB 5.0 MB/s eta 0:00:11
   ---------------------- ----------------- 69.4/122.0 MB 5.0 MB/s eta 0:00:11
   ---------------------- ----------------- 69.6/122.0 MB 5.0 MB/s eta 0:00:11
   ---------------------- ----------------- 69.7/122.0 MB 5.0 MB/s eta 0:00:11
   ---------------------- ----------------- 70.0/122.0 MB 5.0 MB/s eta 0:00:11
   ----------------------- ---------------- 70.2/122.0 MB 5.0 MB/s eta 0:00:11
   ----------------------- ---------------- 70.4/122.0 MB 5.0 MB/s eta 0:00:11
   ----------------------- ---------------- 70.6/122.0 MB 5.0 MB/s eta 0:00:11
   ----------------------- ---------------- 70.9/122.0 MB 5.0 MB/s eta 0:00:11
   ----------------------- ---------------- 71.1/122.0 MB 5.0 MB/s eta 0:00:11
   ----------------------- ---------------- 71.3/122.0 MB 5.0 MB/s eta 0:00:11
   ----------------------- ---------------- 71.6/122.0 MB 5.0 MB/s eta 0:00:11
   ----------------------- ---------------- 71.8/122.0 MB 4.9 MB/s eta 0:00:11
   ----------------------- ---------------- 72.0/122.0 MB 4.9 MB/s eta 0:00:11
   ----------------------- ---------------- 72.2/122.0 MB 4.9 MB/s eta 0:00:11
   ----------------------- ---------------- 72.5/122.0 MB 4.9 MB/s eta 0:00:11
   ----------------------- ---------------- 72.7/122.0 MB 5.1 MB/s eta 0:00:10
   ----------------------- ---------------- 73.0/122.0 MB 5.2 MB/s eta 0:00:10
   ----------------------- ---------------- 73.2/122.0 MB 5.2 MB/s eta 0:00:10
   ------------------------ --------------- 73.3/122.0 MB 5.2 MB/s eta 0:00:10
   ------------------------ --------------- 73.4/122.0 MB 5.1 MB/s eta 0:00:10
   ------------------------ --------------- 73.6/122.0 MB 5.1 MB/s eta 0:00:10
   ------------------------ --------------- 73.7/122.0 MB 5.0 MB/s eta 0:00:10
   ------------------------ --------------- 73.9/122.0 MB 5.0 MB/s eta 0:00:10
   ------------------------ --------------- 74.1/122.0 MB 5.0 MB/s eta 0:00:10
   ------------------------ --------------- 74.2/122.0 MB 4.9 MB/s eta 0:00:10
   ------------------------ --------------- 74.3/122.0 MB 4.9 MB/s eta 0:00:10
   ------------------------ --------------- 74.4/122.0 MB 4.8 MB/s eta 0:00:10
   ------------------------ --------------- 74.5/122.0 MB 4.7 MB/s eta 0:00:11
   ------------------------ --------------- 74.6/122.0 MB 4.7 MB/s eta 0:00:11
   ------------------------ --------------- 74.7/122.0 MB 4.6 MB/s eta 0:00:11
   ------------------------ --------------- 74.9/122.0 MB 4.6 MB/s eta 0:00:11
   ------------------------ --------------- 75.0/122.0 MB 4.5 MB/s eta 0:00:11
   ------------------------ --------------- 75.2/122.0 MB 4.5 MB/s eta 0:00:11
   ------------------------ --------------- 75.3/122.0 MB 4.5 MB/s eta 0:00:11
   ------------------------ --------------- 75.4/122.0 MB 4.5 MB/s eta 0:00:11
   ------------------------ --------------- 75.6/122.0 MB 4.4 MB/s eta 0:00:11
   ------------------------ --------------- 75.7/122.0 MB 4.4 MB/s eta 0:00:11
   ------------------------ --------------- 75.9/122.0 MB 4.4 MB/s eta 0:00:11
   ------------------------ --------------- 76.0/122.0 MB 4.4 MB/s eta 0:00:11
   ------------------------ --------------- 76.1/122.0 MB 4.3 MB/s eta 0:00:11
   ------------------------ --------------- 76.2/122.0 MB 4.3 MB/s eta 0:00:11
   ------------------------- -------------- 76.3/122.0 MB 4.2 MB/s eta 0:00:11

In [ ]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer('all-MiniLM-L6-v2')

print("Model loaded succesfully")
print("Embedding dimension:",model.get_sentence_embedding_dimension())

In [3]:
import torch
print("Torch version:", torch.__version__)
print("Torch loaded fine, testing nn module...")
x = torch.nn.Linear(10, 5)
print("torch.nn works fine")

Torch version: 2.2.2+cpu
Torch loaded fine, testing nn module...
torch.nn works fine

In [4]:
import sys
!{sys.executable} -m pip install --upgrade sentence-transformers transformers

Requirement already satisfied: sentence-transformers in c:\users\famil\anaconda3\lib\site-packages (5.6.0)
Requirement already satisfied: transformers in c:\users\famil\anaconda3\lib\site-packages (5.13.0)
Requirement already satisfied: huggingface-hub>=0.23.0 in c:\users\famil\anaconda3\lib\site-packages (from sentence-transformers) (1.22.0)
Requirement already satisfied: torch>=1.11.0 in c:\users\famil\anaconda3\lib\site-packages (from sentence-transformers) (2.2.2+cpu)
Requirement already satisfied: numpy>=1.20.0 in c:\users\famil\anaconda3\lib\site-packages (from sentence-transformers) (1.26.4)
Requirement already satisfied: scikit-learn>=0.22.0 in c:\users\famil\anaconda3\lib\site-packages (from sentence-transformers) (1.2.2)
Requirement already satisfied: scipy>=1.0.0 in c:\users\famil\anaconda3\lib\site-packages (from sentence-transformers) (1.11.4)
Requirement already satisfied: typing_extensions>=4.5.0 in c:\users\famil\anaconda3\lib\site-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: tqdm>=4.0.0 in c:\users\famil\anaconda3\lib\site-packages (from sentence-transformers) (4.67.3)
Requirement already satisfied: packaging>=20.0 in c:\users\famil\anaconda3\lib\site-packages (from transformers) (23.2)
Requirement already satisfied: pyyaml>=5.1 in c:\users\famil\anaconda3\lib\site-packages (from transformers) (6.0.1)
Requirement already satisfied: regex>=2025.10.22 in c:\users\famil\anaconda3\lib\site-packages (from transformers) (2026.1.15)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in c:\users\famil\anaconda3\lib\site-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in c:\users\famil\anaconda3\lib\site-packages (from transformers) (0.20.0)
Requirement already satisfied: safetensors>=0.8.0 in c:\users\famil\anaconda3\lib\site-packages (from transformers) (0.8.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in c:\users\famil\anaconda3\lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (8.4.2)
Requirement already satisfied: filelock>=3.10.0 in c:\users\famil\anaconda3\lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (3.13.1)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\famil\anaconda3\lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (2023.10.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in c:\users\famil\anaconda3\lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\famil\anaconda3\lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.28.1)
Requirement already satisfied: joblib>=1.1.1 in c:\users\famil\anaconda3\lib\site-packages (from scikit-learn>=0.22.0->sentence-transformers) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\famil\anaconda3\lib\site-packages (from scikit-learn>=0.22.0->sentence-transformers) (2.2.0)
Requirement already satisfied: sympy in c:\users\famil\anaconda3\lib\site-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx in c:\users\famil\anaconda3\lib\site-packages (from torch>=1.11.0->sentence-transformers) (3.1)
Requirement already satisfied: jinja2 in c:\users\famil\anaconda3\lib\site-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: colorama in c:\users\famil\anaconda3\lib\site-packages (from tqdm>=4.0.0->sentence-transformers) (0.4.6)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\famil\anaconda3\lib\site-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in c:\users\famil\anaconda3\lib\site-packages (from typer->transformers) (13.9.4)
Requirement already satisfied: anyio in c:\users\famil\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (4.13.0)
Requirement already satisfied: certifi in c:\users\famil\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (2026.2.25)
Requirement already satisfied: httpcore==1.* in c:\users\famil\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in c:\users\famil\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (3.11)
Requirement already satisfied: h11>=0.16 in c:\users\famil\anaconda3\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\famil\anaconda3\lib\site-packages (from rich>=10.11.0->typer->transformers) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\famil\anaconda3\lib\site-packages (from rich>=10.11.0->typer->transformers) (2.19.2)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\famil\anaconda3\lib\site-packages (from jinja2->torch>=1.11.0->sentence-transformers) (2.1.3)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\famil\anaconda3\lib\site-packages (from sympy->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: mdurl~=0.1 in c:\users\famil\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer->transformers) (0.1.0)

In [3]:
import sys
!{sys.executable} -m pip uninstall torch -y
!{sys.executable} -m pip install torch==2.2.2 --index-url https://download.pytorch.org/whl/cpu

Found existing installation: torch 2.13.0+cpu
Uninstalling torch-2.13.0+cpu:
  Successfully uninstalled torch-2.13.0+cpu
Looking in indexes: https://download.pytorch.org/whl/cpu
Collecting torch==2.2.2
  Downloading https://download-r2.pytorch.org/whl/cpu/torch-2.2.2%2Bcpu-cp311-cp311-win_amd64.whl (200.8 MB)
     ---------------------------------------- 0.0/200.8 MB ? eta -:--:--
     ---------------------------------------- 0.1/200.8 MB 2.9 MB/s eta 0:01:10
     ---------------------------------------- 0.2/200.8 MB 1.9 MB/s eta 0:01:44
     ---------------------------------------- 0.3/200.8 MB 2.3 MB/s eta 0:01:28
     ---------------------------------------- 0.3/200.8 MB 2.0 MB/s eta 0:01:40
     ---------------------------------------- 0.4/200.8 MB 1.9 MB/s eta 0:01:45
     ---------------------------------------- 0.5/200.8 MB 1.9 MB/s eta 0:01:47
     ---------------------------------------- 0.5/200.8 MB 1.8 MB/s eta 0:01:52
     ---------------------------------------- 0.6/200.8 MB 1.8 MB/s eta 0:01:54
     ---------------------------------------- 0.6/200.8 MB 1.8 MB/s eta 0:01:54
     ---------------------------------------- 0.6/200.8 MB 1.5 MB/s eta 0:02:18
     ---------------------------------------- 0.6/200.8 MB 1.5 MB/s eta 0:02:18
     ---------------------------------------- 0.6/200.8 MB 1.5 MB/s eta 0:02:18
     ---------------------------------------- 0.6/200.8 MB 1.2 MB/s eta 0:02:53
     ---------------------------------------- 0.6/200.8 MB 1.2 MB/s eta 0:02:53
     ---------------------------------------- 0.7/200.8 MB 1.1 MB/s eta 0:03:04
     ---------------------------------------- 0.7/200.8 MB 1.1 MB/s eta 0:03:01
     -------------------------------------- 0.8/200.8 MB 996.7 kB/s eta 0:03:21
     ---------------------------------------- 1.0/200.8 MB 1.2 MB/s eta 0:02:50
     ---------------------------------------- 1.1/200.8 MB 1.3 MB/s eta 0:02:34
     ---------------------------------------- 1.2/200.8 MB 1.4 MB/s eta 0:02:26
     ---------------------------------------- 1.4/200.8 MB 1.5 MB/s eta 0:02:17
     ---------------------------------------- 1.5/200.8 MB 1.5 MB/s eta 0:02:10
     ---------------------------------------- 1.7/200.8 MB 1.7 MB/s eta 0:02:01
     ---------------------------------------- 1.8/200.8 MB 1.7 MB/s eta 0:02:01
     ---------------------------------------- 1.9/200.8 MB 1.7 MB/s eta 0:01:55
     ---------------------------------------- 2.1/200.8 MB 1.8 MB/s eta 0:01:51
     ---------------------------------------- 2.2/200.8 MB 1.8 MB/s eta 0:01:48
     ---------------------------------------- 2.4/200.8 MB 1.9 MB/s eta 0:01:44
     ---------------------------------------- 2.5/200.8 MB 1.9 MB/s eta 0:01:42
      --------------------------------------- 2.7/200.8 MB 2.0 MB/s eta 0:01:40
      --------------------------------------- 2.9/200.8 MB 2.1 MB/s eta 0:01:35
      --------------------------------------- 3.0/200.8 MB 2.1 MB/s eta 0:01:36
      --------------------------------------- 3.1/200.8 MB 2.1 MB/s eta 0:01:34
      --------------------------------------- 3.3/200.8 MB 2.1 MB/s eta 0:01:32
      --------------------------------------- 3.4/200.8 MB 2.2 MB/s eta 0:01:30
      --------------------------------------- 3.6/200.8 MB 2.2 MB/s eta 0:01:29
      --------------------------------------- 3.7/200.8 MB 2.2 MB/s eta 0:01:29
      --------------------------------------- 3.9/200.8 MB 2.3 MB/s eta 0:01:27
      --------------------------------------- 4.1/200.8 MB 2.3 MB/s eta 0:01:25
      --------------------------------------- 4.1/200.8 MB 2.3 MB/s eta 0:01:25
      --------------------------------------- 4.2/200.8 MB 2.3 MB/s eta 0:01:26
      --------------------------------------- 4.3/200.8 MB 2.3 MB/s eta 0:01:26
      --------------------------------------- 4.4/200.8 MB 2.3 MB/s eta 0:01:26
      --------------------------------------- 4.4/200.8 MB 2.3 MB/s eta 0:01:28
      --------------------------------------- 4.5/200.8 MB 2.3 MB/s eta 0:01:28
      --------------------------------------- 4.7/200.8 MB 2.3 MB/s eta 0:01:26
      --------------------------------------- 4.8/200.8 MB 2.3 MB/s eta 0:01:27
      --------------------------------------- 5.0/200.8 MB 2.3 MB/s eta 0:01:25
     - -------------------------------------- 5.2/200.8 MB 2.3 MB/s eta 0:01:24
     - -------------------------------------- 5.3/200.8 MB 2.4 MB/s eta 0:01:24
     - -------------------------------------- 5.3/200.8 MB 2.3 MB/s eta 0:01:25
     - -------------------------------------- 5.4/200.8 MB 2.3 MB/s eta 0:01:25
     - -------------------------------------- 5.5/200.8 MB 2.3 MB/s eta 0:01:25
     - -------------------------------------- 5.7/200.8 MB 2.3 MB/s eta 0:01:25
     - -------------------------------------- 5.8/200.8 MB 2.3 MB/s eta 0:01:24
     - -------------------------------------- 6.0/200.8 MB 2.4 MB/s eta 0:01:22
     - -------------------------------------- 6.2/200.8 MB 2.4 MB/s eta 0:01:21
     - -------------------------------------- 6.3/200.8 MB 2.4 MB/s eta 0:01:21
     - -------------------------------------- 6.5/200.8 MB 2.4 MB/s eta 0:01:20
     - -------------------------------------- 6.6/200.8 MB 2.4 MB/s eta 0:01:21
     - -------------------------------------- 6.8/200.8 MB 2.5 MB/s eta 0:01:20
     - -------------------------------------- 7.0/200.8 MB 2.5 MB/s eta 0:01:19
     - -------------------------------------- 7.1/200.8 MB 2.5 MB/s eta 0:01:18
     - -------------------------------------- 7.2/200.8 MB 2.5 MB/s eta 0:01:17
     - -------------------------------------- 7.2/200.8 MB 2.5 MB/s eta 0:01:17
     - -------------------------------------- 7.5/200.8 MB 2.5 MB/s eta 0:01:17
     - -------------------------------------- 7.6/200.8 MB 2.5 MB/s eta 0:01:18
     - -------------------------------------- 7.8/200.8 MB 2.5 MB/s eta 0:01:17
     - -------------------------------------- 7.9/200.8 MB 2.5 MB/s eta 0:01:16
     - -------------------------------------- 8.1/200.8 MB 2.6 MB/s eta 0:01:15
     - -------------------------------------- 8.2/200.8 MB 2.6 MB/s eta 0:01:15
     - -------------------------------------- 8.4/200.8 MB 2.6 MB/s eta 0:01:15
     - -------------------------------------- 8.5/200.8 MB 2.6 MB/s eta 0:01:15
     - -------------------------------------- 8.7/200.8 MB 2.6 MB/s eta 0:01:14
     - -------------------------------------- 8.8/200.8 MB 2.6 MB/s eta 0:01:14
     - -------------------------------------- 9.1/200.8 MB 2.6 MB/s eta 0:01:13
     - -------------------------------------- 9.2/200.8 MB 2.7 MB/s eta 0:01:13
     - -------------------------------------- 9.5/200.8 MB 2.7 MB/s eta 0:01:12
     - -------------------------------------- 9.6/200.8 MB 2.7 MB/s eta 0:01:12
     - -------------------------------------- 9.9/200.8 MB 2.7 MB/s eta 0:01:11
     - ------------------------------------- 10.0/200.8 MB 2.8 MB/s eta 0:01:10
     - ------------------------------------- 10.2/200.8 MB 2.8 MB/s eta 0:01:09
     -- ------------------------------------ 10.4/200.8 MB 2.8 MB/s eta 0:01:08
     -- ------------------------------------ 10.6/200.8 MB 2.9 MB/s eta 0:01:07
     -- ------------------------------------ 10.7/200.8 MB 2.9 MB/s eta 0:01:06
     -- ------------------------------------ 10.8/200.8 MB 2.8 MB/s eta 0:01:08
     -- ------------------------------------ 10.8/200.8 MB 2.9 MB/s eta 0:01:05
     -- ------------------------------------ 10.9/200.8 MB 3.1 MB/s eta 0:01:02
     -- ------------------------------------ 11.2/200.8 MB 3.2 MB/s eta 0:01:00
     -- ------------------------------------ 11.2/200.8 MB 3.2 MB/s eta 0:01:00
     -- ------------------------------------ 11.3/200.8 MB 3.1 MB/s eta 0:01:01
     -- ------------------------------------ 11.5/200.8 MB 3.1 MB/s eta 0:01:01
     -- ------------------------------------ 11.6/200.8 MB 3.1 MB/s eta 0:01:01
     -- ------------------------------------ 11.9/200.8 MB 3.2 MB/s eta 0:01:00
     -- ------------------------------------ 11.9/200.8 MB 3.1 MB/s eta 0:01:01
     -- ------------------------------------ 12.1/200.8 MB 3.2 MB/s eta 0:01:00
     -- ------------------------------------ 12.2/200.8 MB 3.2 MB/s eta 0:01:00
     -- ------------------------------------ 12.3/200.8 MB 3.1 MB/s eta 0:01:01
     -- ------------------------------------ 12.5/200.8 MB 3.1 MB/s eta 0:01:00
     -- ------------------------------------ 12.6/200.8 MB 3.1 MB/s eta 0:01:01
     -- ------------------------------------ 12.8/200.8 MB 3.1 MB/s eta 0:01:01
     -- ------------------------------------ 12.9/200.8 MB 3.1 MB/s eta 0:01:01
     -- ------------------------------------ 13.0/200.8 MB 3.1 MB/s eta 0:01:01
     -- ------------------------------------ 13.2/200.8 MB 3.1 MB/s eta 0:01:01
     -- ------------------------------------ 13.3/200.8 MB 3.1 MB/s eta 0:01:01
     -- ------------------------------------ 13.4/200.8 MB 3.1 MB/s eta 0:01:01
     -- ------------------------------------ 13.5/200.8 MB 3.1 MB/s eta 0:01:01
     -- ------------------------------------ 13.7/200.8 MB 3.1 MB/s eta 0:01:01
     -- ------------------------------------ 13.8/200.8 MB 3.1 MB/s eta 0:01:01
     -- ------------------------------------ 14.0/200.8 MB 3.1 MB/s eta 0:01:01
     -- ------------------------------------ 14.1/200.8 MB 3.1 MB/s eta 0:01:01
     -- ------------------------------------ 14.2/200.8 MB 3.1 MB/s eta 0:01:01
     -- ------------------------------------ 14.3/200.8 MB 3.0 MB/s eta 0:01:02
     -- ------------------------------------ 14.3/200.8 MB 3.1 MB/s eta 0:01:01
     -- ------------------------------------ 14.4/200.8 MB 3.0 MB/s eta 0:01:02
     -- ------------------------------------ 14.5/200.8 MB 3.0 MB/s eta 0:01:02
     -- ------------------------------------ 14.6/200.8 MB 3.1 MB/s eta 0:01:01
     -- ------------------------------------ 14.7/200.8 MB 3.0 MB/s eta 0:01:02
     -- ------------------------------------ 14.7/200.8 MB 3.0 MB/s eta 0:01:02
     -- ------------------------------------ 14.8/200.8 MB 3.0 MB/s eta 0:01:02
     -- ------------------------------------ 15.0/200.8 MB 3.0 MB/s eta 0:01:02
     -- ------------------------------------ 15.1/200.8 MB 3.0 MB/s eta 0:01:02
     -- ------------------------------------ 15.3/200.8 MB 3.0 MB/s eta 0:01:02
     -- ------------------------------------ 15.4/200.8 MB 3.0 MB/s eta 0:01:02
     --- ----------------------------------- 15.5/200.8 MB 3.0 MB/s eta 0:01:01
     --- ----------------------------------- 15.6/200.8 MB 3.1 MB/s eta 0:01:01
     --- ----------------------------------- 15.8/200.8 MB 3.1 MB/s eta 0:01:01
     --- ----------------------------------- 16.0/200.8 MB 3.1 MB/s eta 0:01:01
     --- ----------------------------------- 16.1/200.8 MB 3.1 MB/s eta 0:01:01
     --- ----------------------------------- 16.2/200.8 MB 3.0 MB/s eta 0:01:01
     --- ----------------------------------- 16.3/200.8 MB 3.0 MB/s eta 0:01:01
     --- ----------------------------------- 16.4/200.8 MB 3.0 MB/s eta 0:01:01
     --- ----------------------------------- 16.6/200.8 MB 3.0 MB/s eta 0:01:02
     --- ----------------------------------- 16.7/200.8 MB 3.0 MB/s eta 0:01:01
     --- ----------------------------------- 16.9/200.8 MB 3.0 MB/s eta 0:01:01
     --- ----------------------------------- 17.0/200.8 MB 3.0 MB/s eta 0:01:02
     --- ----------------------------------- 17.1/200.8 MB 3.0 MB/s eta 0:01:02
     --- ----------------------------------- 17.1/200.8 MB 3.0 MB/s eta 0:01:02
     --- ----------------------------------- 17.1/200.8 MB 2.9 MB/s eta 0:01:03
     --- ----------------------------------- 17.2/200.8 MB 2.9 MB/s eta 0:01:04
     --- ----------------------------------- 17.3/200.8 MB 2.9 MB/s eta 0:01:04
     --- ----------------------------------- 17.4/200.8 MB 2.9 MB/s eta 0:01:04
     --- ----------------------------------- 17.5/200.8 MB 2.9 MB/s eta 0:01:03
     --- ----------------------------------- 17.6/200.8 MB 2.9 MB/s eta 0:01:04
     --- ----------------------------------- 17.7/200.8 MB 2.9 MB/s eta 0:01:05
     --- ----------------------------------- 17.9/200.8 MB 2.9 MB/s eta 0:01:04
     --- ----------------------------------- 18.0/200.8 MB 2.8 MB/s eta 0:01:05
     --- ----------------------------------- 18.1/200.8 MB 2.8 MB/s eta 0:01:05
     --- ----------------------------------- 18.1/200.8 MB 2.8 MB/s eta 0:01:05
     --- ----------------------------------- 18.3/200.8 MB 2.8 MB/s eta 0:01:05
     --- ----------------------------------- 18.4/200.8 MB 2.8 MB/s eta 0:01:06
     --- ----------------------------------- 18.5/200.8 MB 2.8 MB/s eta 0:01:06
     --- ----------------------------------- 18.6/200.8 MB 2.8 MB/s eta 0:01:06
     --- ----------------------------------- 18.7/200.8 MB 2.8 MB/s eta 0:01:07
     --- ----------------------------------- 18.8/200.8 MB 2.8 MB/s eta 0:01:06
     --- ----------------------------------- 18.9/200.8 MB 2.8 MB/s eta 0:01:07
     --- ----------------------------------- 19.0/200.8 MB 2.7 MB/s eta 0:01:07
     --- ----------------------------------- 19.1/200.8 MB 2.7 MB/s eta 0:01:07
     --- ----------------------------------- 19.2/200.8 MB 2.7 MB/s eta 0:01:07
     --- ----------------------------------- 19.3/200.8 MB 2.7 MB/s eta 0:01:08
     --- ----------------------------------- 19.4/200.8 MB 2.7 MB/s eta 0:01:08
     --- ----------------------------------- 19.4/200.8 MB 2.7 MB/s eta 0:01:08
     --- ----------------------------------- 19.4/200.8 MB 2.7 MB/s eta 0:01:08
     --- ----------------------------------- 19.6/200.8 MB 2.6 MB/s eta 0:01:09
     --- ----------------------------------- 19.7/200.8 MB 2.6 MB/s eta 0:01:10
     --- ----------------------------------- 19.8/200.8 MB 2.6 MB/s eta 0:01:10
     --- ----------------------------------- 19.9/200.8 MB 2.6 MB/s eta 0:01:11
     --- ----------------------------------- 20.0/200.8 MB 2.5 MB/s eta 0:01:11
     --- ----------------------------------- 20.1/200.8 MB 2.5 MB/s eta 0:01:12
     --- ----------------------------------- 20.2/200.8 MB 2.5 MB/s eta 0:01:13
     --- ----------------------------------- 20.3/200.8 MB 2.5 MB/s eta 0:01:12
     --- ----------------------------------- 20.4/200.8 MB 2.5 MB/s eta 0:01:13
     --- ----------------------------------- 20.5/200.8 MB 2.5 MB/s eta 0:01:13
     ---- ---------------------------------- 20.6/200.8 MB 2.5 MB/s eta 0:01:14
     ---- ---------------------------------- 20.7/200.8 MB 2.5 MB/s eta 0:01:14
     ---- ---------------------------------- 20.8/200.8 MB 2.4 MB/s eta 0:01:14
     ---- ---------------------------------- 20.9/200.8 MB 2.4 MB/s eta 0:01:15
     ---- ---------------------------------- 21.0/200.8 MB 2.4 MB/s eta 0:01:15
     ---- ---------------------------------- 21.1/200.8 MB 2.5 MB/s eta 0:01:14
     ---- ---------------------------------- 21.2/200.8 MB 2.4 MB/s eta 0:01:14
     ---- ---------------------------------- 21.3/200.8 MB 2.4 MB/s eta 0:01:15
     ---- ---------------------------------- 21.3/200.8 MB 2.4 MB/s eta 0:01:15
     ---- ---------------------------------- 21.4/200.8 MB 2.4 MB/s eta 0:01:16
     ---- ---------------------------------- 21.5/200.8 MB 2.4 MB/s eta 0:01:15
     ---- ---------------------------------- 21.6/200.8 MB 2.4 MB/s eta 0:01:16
     ---- ---------------------------------- 21.6/200.8 MB 2.4 MB/s eta 0:01:16
     ---- ---------------------------------- 21.6/200.8 MB 2.4 MB/s eta 0:01:16
     ---- ---------------------------------- 21.6/200.8 MB 2.3 MB/s eta 0:01:17
     ---- ---------------------------------- 21.7/200.8 MB 2.3 MB/s eta 0:01:18
     ---- ---------------------------------- 21.8/200.8 MB 2.3 MB/s eta 0:01:18
     ---- ---------------------------------- 21.9/200.8 MB 2.3 MB/s eta 0:01:19
     ---- ---------------------------------- 22.0/200.8 MB 2.3 MB/s eta 0:01:19
     ---- ---------------------------------- 22.1/200.8 MB 2.3 MB/s eta 0:01:19
     ---- ---------------------------------- 22.2/200.8 MB 2.3 MB/s eta 0:01:19
     ---- ---------------------------------- 22.3/200.8 MB 2.3 MB/s eta 0:01:19
     ---- ---------------------------------- 22.4/200.8 MB 2.3 MB/s eta 0:01:20
     ---- ---------------------------------- 22.5/200.8 MB 2.3 MB/s eta 0:01:19
     ---- ---------------------------------- 22.6/200.8 MB 2.3 MB/s eta 0:01:19
     ---- ---------------------------------- 22.8/200.8 MB 2.3 MB/s eta 0:01:19
     ---- ---------------------------------- 22.9/200.8 MB 2.2 MB/s eta 0:01:20
     ---- ---------------------------------- 23.0/200.8 MB 2.2 MB/s eta 0:01:20
     ---- ---------------------------------- 23.1/200.8 MB 2.2 MB/s eta 0:01:20
     ---- ---------------------------------- 23.2/200.8 MB 2.2 MB/s eta 0:01:20
     ---- ---------------------------------- 23.3/200.8 MB 2.2 MB/s eta 0:01:20
     ---- ---------------------------------- 23.4/200.8 MB 2.2 MB/s eta 0:01:20
     ---- ---------------------------------- 23.5/200.8 MB 2.2 MB/s eta 0:01:21
     ---- ---------------------------------- 23.6/200.8 MB 2.2 MB/s eta 0:01:21
     ---- ---------------------------------- 23.7/200.8 MB 2.2 MB/s eta 0:01:21
     ---- ---------------------------------- 23.8/200.8 MB 2.2 MB/s eta 0:01:21
     ---- ---------------------------------- 23.9/200.8 MB 2.2 MB/s eta 0:01:21
     ---- ---------------------------------- 24.0/200.8 MB 2.2 MB/s eta 0:01:21
     ---- ---------------------------------- 24.1/200.8 MB 2.2 MB/s eta 0:01:21
     ---- ---------------------------------- 24.1/200.8 MB 2.2 MB/s eta 0:01:21
     ---- ---------------------------------- 24.1/200.8 MB 2.2 MB/s eta 0:01:21
     ---- ---------------------------------- 24.3/200.8 MB 2.1 MB/s eta 0:01:23
     ---- ---------------------------------- 24.4/200.8 MB 2.1 MB/s eta 0:01:23
     ---- ---------------------------------- 24.5/200.8 MB 2.2 MB/s eta 0:01:22
     ---- ---------------------------------- 24.6/200.8 MB 2.2 MB/s eta 0:01:22
     ---- ---------------------------------- 24.7/200.8 MB 2.2 MB/s eta 0:01:22
     ---- ---------------------------------- 24.8/200.8 MB 2.2 MB/s eta 0:01:22
     ---- ---------------------------------- 24.9/200.8 MB 2.2 MB/s eta 0:01:22
     ---- ---------------------------------- 25.0/200.8 MB 2.2 MB/s eta 0:01:21
     ---- ---------------------------------- 25.1/200.8 MB 2.2 MB/s eta 0:01:21
     ---- ---------------------------------- 25.2/200.8 MB 2.2 MB/s eta 0:01:22
     ---- ---------------------------------- 25.2/200.8 MB 2.2 MB/s eta 0:01:22
     ---- ---------------------------------- 25.3/200.8 MB 2.2 MB/s eta 0:01:22
     ---- ---------------------------------- 25.4/200.8 MB 2.1 MB/s eta 0:01:22
     ---- ---------------------------------- 25.5/200.8 MB 2.1 MB/s eta 0:01:22
     ---- ---------------------------------- 25.6/200.8 MB 2.1 MB/s eta 0:01:23
     ---- ---------------------------------- 25.7/200.8 MB 2.1 MB/s eta 0:01:23
     ----- --------------------------------- 25.8/200.8 MB 2.1 MB/s eta 0:01:23
     ----- --------------------------------- 25.9/200.8 MB 2.1 MB/s eta 0:01:23
     ----- --------------------------------- 26.0/200.8 MB 2.1 MB/s eta 0:01:23
     ----- --------------------------------- 26.1/200.8 MB 2.1 MB/s eta 0:01:23
     ----- --------------------------------- 26.2/200.8 MB 2.1 MB/s eta 0:01:24
     ----- --------------------------------- 26.3/200.8 MB 2.1 MB/s eta 0:01:24
     ----- --------------------------------- 26.4/200.8 MB 2.1 MB/s eta 0:01:24
     ----- --------------------------------- 26.5/200.8 MB 2.1 MB/s eta 0:01:25
     ----- --------------------------------- 26.6/200.8 MB 2.1 MB/s eta 0:01:24
     ----- --------------------------------- 26.7/200.8 MB 2.1 MB/s eta 0:01:25
     ----- --------------------------------- 26.8/200.8 MB 2.1 MB/s eta 0:01:25
     ----- --------------------------------- 26.9/200.8 MB 2.1 MB/s eta 0:01:25
     ----- --------------------------------- 27.0/200.8 MB 2.1 MB/s eta 0:01:25
     ----- --------------------------------- 27.1/200.8 MB 2.0 MB/s eta 0:01:25
     ----- --------------------------------- 27.2/200.8 MB 2.0 MB/s eta 0:01:25

In [4]:
!{sys.executable} -m pip install torch --index-url https://download.pytorch.org/whl/cpu

Looking in indexes: https://download.pytorch.org/whl/cpu
Collecting torch
  Downloading https://download-r2.pytorch.org/whl/cpu/torch-2.13.0%2Bcpu-cp311-cp311-win_amd64.whl.metadata (39 kB)
Requirement already satisfied: filelock in c:\users\famil\anaconda3\lib\site-packages (from torch) (3.13.1)
Requirement already satisfied: typing-extensions>=4.10.0 in c:\users\famil\anaconda3\lib\site-packages (from torch) (4.15.0)
Requirement already satisfied: setuptools>=77.0.3 in c:\users\famil\anaconda3\lib\site-packages (from torch) (83.0.0)
Requirement already satisfied: sympy>=1.13.3 in c:\users\famil\anaconda3\lib\site-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in c:\users\famil\anaconda3\lib\site-packages (from torch) (3.1)
Requirement already satisfied: jinja2 in c:\users\famil\anaconda3\lib\site-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in c:\users\famil\anaconda3\lib\site-packages (from torch) (2023.10.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\famil\anaconda3\lib\site-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\famil\anaconda3\lib\site-packages (from jinja2->torch) (2.1.3)
Downloading https://download-r2.pytorch.org/whl/cpu/torch-2.13.0%2Bcpu-cp311-cp311-win_amd64.whl (121.9 MB)
   ---------------------------------------- 0.0/121.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/121.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/121.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/121.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/121.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/121.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/121.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/121.9 MB 320.0 kB/s eta 0:06:21
   ---------------------------------------- 0.0/121.9 MB 320.0 kB/s eta 0:06:21
   ---------------------------------------- 0.0/121.9 MB 320.0 kB/s eta 0:06:21
   ---------------------------------------- 0.0/121.9 MB 320.0 kB/s eta 0:06:21
   ---------------------------------------- 0.0/121.9 MB 320.0 kB/s eta 0:06:21
   ---------------------------------------- 0.0/121.9 MB 72.6 kB/s eta 0:27:58
   ---------------------------------------- 0.0/121.9 MB 72.6 kB/s eta 0:27:58
   ---------------------------------------- 0.0/121.9 MB 72.6 kB/s eta 0:27:58
   ---------------------------------------- 0.0/121.9 MB 72.6 kB/s eta 0:27:58
   ---------------------------------------- 0.0/121.9 MB 72.6 kB/s eta 0:27:58
   ---------------------------------------- 0.0/121.9 MB 72.6 kB/s eta 0:27:58
   ---------------------------------------- 0.0/121.9 MB 54.6 kB/s eta 0:37:14
   ---------------------------------------- 0.0/121.9 MB 54.6 kB/s eta 0:37:14
   ---------------------------------------- 0.0/121.9 MB 54.6 kB/s eta 0:37:14
   ---------------------------------------- 0.0/121.9 MB 54.6 kB/s eta 0:37:14
   ---------------------------------------- 0.0/121.9 MB 54.6 kB/s eta 0:37:14
   ---------------------------------------- 0.0/121.9 MB 54.6 kB/s eta 0:37:14
   ---------------------------------------- 0.0/121.9 MB 54.6 kB/s eta 0:37:14
   ---------------------------------------- 0.0/121.9 MB 54.6 kB/s eta 0:37:14
   ---------------------------------------- 0.0/121.9 MB 54.6 kB/s eta 0:37:14
   ---------------------------------------- 0.0/121.9 MB 54.6 kB/s eta 0:37:14
   ---------------------------------------- 0.0/121.9 MB 54.6 kB/s eta 0:37:14
   ---------------------------------------- 0.1/121.9 MB 37.4 kB/s eta 0:54:15
   ---------------------------------------- 0.1/121.9 MB 45.5 kB/s eta 0:44:37
   ---------------------------------------- 0.1/121.9 MB 45.5 kB/s eta 0:44:37
   ---------------------------------------- 0.1/121.9 MB 45.5 kB/s eta 0:44:37
   ---------------------------------------- 0.1/121.9 MB 45.5 kB/s eta 0:44:37
   ---------------------------------------- 0.1/121.9 MB 45.5 kB/s eta 0:44:37
   ---------------------------------------- 0.1/121.9 MB 45.2 kB/s eta 0:44:57
   ---------------------------------------- 0.1/121.9 MB 45.2 kB/s eta 0:44:57
   ---------------------------------------- 0.1/121.9 MB 45.2 kB/s eta 0:44:57
   ---------------------------------------- 0.1/121.9 MB 45.2 kB/s eta 0:44:57
   ---------------------------------------- 0.1/121.9 MB 45.2 kB/s eta 0:44:57
   ---------------------------------------- 0.1/121.9 MB 45.2 kB/s eta 0:44:57
   ---------------------------------------- 0.1/121.9 MB 49.9 kB/s eta 0:40:40
   ---------------------------------------- 0.1/121.9 MB 49.9 kB/s eta 0:40:40
   ---------------------------------------- 0.1/121.9 MB 49.9 kB/s eta 0:40:40
   ---------------------------------------- 0.1/121.9 MB 49.9 kB/s eta 0:40:40
   ---------------------------------------- 0.1/121.9 MB 49.9 kB/s eta 0:40:40
   ---------------------------------------- 0.1/121.9 MB 49.9 kB/s eta 0:40:40
   ---------------------------------------- 0.1/121.9 MB 48.3 kB/s eta 0:42:01
   ---------------------------------------- 0.1/121.9 MB 48.3 kB/s eta 0:42:01
   ---------------------------------------- 0.1/121.9 MB 48.3 kB/s eta 0:42:01
   ---------------------------------------- 0.1/121.9 MB 48.3 kB/s eta 0:42:01
   ---------------------------------------- 0.1/121.9 MB 48.3 kB/s eta 0:42:01
   ---------------------------------------- 0.1/121.9 MB 51.9 kB/s eta 0:39:09
   ---------------------------------------- 0.1/121.9 MB 51.9 kB/s eta 0:39:09
   ---------------------------------------- 0.1/121.9 MB 51.9 kB/s eta 0:39:09
   ---------------------------------------- 0.1/121.9 MB 51.9 kB/s eta 0:39:09
   ---------------------------------------- 0.1/121.9 MB 51.9 kB/s eta 0:39:09
   ---------------------------------------- 0.1/121.9 MB 51.9 kB/s eta 0:39:09
   ---------------------------------------- 0.1/121.9 MB 50.4 kB/s eta 0:40:16
   ---------------------------------------- 0.1/121.9 MB 53.6 kB/s eta 0:37:53
   ---------------------------------------- 0.1/121.9 MB 53.6 kB/s eta 0:37:53
   ---------------------------------------- 0.1/121.9 MB 53.6 kB/s eta 0:37:53
   ---------------------------------------- 0.1/121.9 MB 53.6 kB/s eta 0:37:53
   ---------------------------------------- 0.1/121.9 MB 53.6 kB/s eta 0:37:53
   ---------------------------------------- 0.2/121.9 MB 52.7 kB/s eta 0:38:29
   ---------------------------------------- 0.2/121.9 MB 52.7 kB/s eta 0:38:29
   ---------------------------------------- 0.2/121.9 MB 52.7 kB/s eta 0:38:29
   ---------------------------------------- 0.2/121.9 MB 52.7 kB/s eta 0:38:29
   ---------------------------------------- 0.2/121.9 MB 52.7 kB/s eta 0:38:29
   ---------------------------------------- 0.2/121.9 MB 52.7 kB/s eta 0:38:29
   ---------------------------------------- 0.2/121.9 MB 54.6 kB/s eta 0:37:09
   ---------------------------------------- 0.2/121.9 MB 54.6 kB/s eta 0:37:09
   ---------------------------------------- 0.2/121.9 MB 54.6 kB/s eta 0:37:09
   ---------------------------------------- 0.2/121.9 MB 54.6 kB/s eta 0:37:09
   ---------------------------------------- 0.2/121.9 MB 54.6 kB/s eta 0:37:09
   ---------------------------------------- 0.2/121.9 MB 54.6 kB/s eta 0:37:09
   ---------------------------------------- 0.2/121.9 MB 56.4 kB/s eta 0:35:57
   ---------------------------------------- 0.2/121.9 MB 56.4 kB/s eta 0:35:57
   ---------------------------------------- 0.2/121.9 MB 56.4 kB/s eta 0:35:57
   ---------------------------------------- 0.2/121.9 MB 56.4 kB/s eta 0:35:57
   ---------------------------------------- 0.2/121.9 MB 56.4 kB/s eta 0:35:57
   ---------------------------------------- 0.2/121.9 MB 56.4 kB/s eta 0:35:57
   ---------------------------------------- 0.2/121.9 MB 55.1 kB/s eta 0:36:50
   ---------------------------------------- 0.2/121.9 MB 55.1 kB/s eta 0:36:50
   ---------------------------------------- 0.2/121.9 MB 55.1 kB/s eta 0:36:50
   ---------------------------------------- 0.2/121.9 MB 55.1 kB/s eta 0:36:50
   ---------------------------------------- 0.2/121.9 MB 55.1 kB/s eta 0:36:50
   ---------------------------------------- 0.2/121.9 MB 56.6 kB/s eta 0:35:49
   ---------------------------------------- 0.2/121.9 MB 56.6 kB/s eta 0:35:49
   ---------------------------------------- 0.2/121.9 MB 56.6 kB/s eta 0:35:49
   ---------------------------------------- 0.2/121.9 MB 56.6 kB/s eta 0:35:49
   ---------------------------------------- 0.2/121.9 MB 56.6 kB/s eta 0:35:49
   ---------------------------------------- 0.2/121.9 MB 56.6 kB/s eta 0:35:49
   ---------------------------------------- 0.2/121.9 MB 58.0 kB/s eta 0:34:59
   ---------------------------------------- 0.2/121.9 MB 58.0 kB/s eta 0:34:59
   ---------------------------------------- 0.2/121.9 MB 58.0 kB/s eta 0:34:59
   ---------------------------------------- 0.2/121.9 MB 58.0 kB/s eta 0:34:59
   ---------------------------------------- 0.3/121.9 MB 57.8 kB/s eta 0:35:04
   ---------------------------------------- 0.3/121.9 MB 57.8 kB/s eta 0:35:04
   ---------------------------------------- 0.3/121.9 MB 57.8 kB/s eta 0:35:04
   ---------------------------------------- 0.3/121.9 MB 57.8 kB/s eta 0:35:04
   ---------------------------------------- 0.3/121.9 MB 60.0 kB/s eta 0:33:48
   ---------------------------------------- 0.3/121.9 MB 60.0 kB/s eta 0:33:48
   ---------------------------------------- 0.3/121.9 MB 60.0 kB/s eta 0:33:48
   ---------------------------------------- 0.3/121.9 MB 60.0 kB/s eta 0:33:48
   ---------------------------------------- 0.3/121.9 MB 60.0 kB/s eta 0:33:48
   ---------------------------------------- 0.3/121.9 MB 60.0 kB/s eta 0:33:48
   ---------------------------------------- 0.3/121.9 MB 60.0 kB/s eta 0:33:48
   ---------------------------------------- 0.3/121.9 MB 62.5 kB/s eta 0:32:25
   ---------------------------------------- 0.3/121.9 MB 62.5 kB/s eta 0:32:25
   ---------------------------------------- 0.3/121.9 MB 65.3 kB/s eta 0:31:02
   ---------------------------------------- 0.3/121.9 MB 65.3 kB/s eta 0:31:02
   ---------------------------------------- 0.3/121.9 MB 66.4 kB/s eta 0:30:32
   ---------------------------------------- 0.3/121.9 MB 66.4 kB/s eta 0:30:32
   ---------------------------------------- 0.4/121.9 MB 69.0 kB/s eta 0:29:22
   ---------------------------------------- 0.4/121.9 MB 70.4 kB/s eta 0:28:48
   ---------------------------------------- 0.4/121.9 MB 70.4 kB/s eta 0:28:48
   ---------------------------------------- 0.4/121.9 MB 73.3 kB/s eta 0:27:39
   ---------------------------------------- 0.4/121.9 MB 76.3 kB/s eta 0:26:33
   ---------------------------------------- 0.4/121.9 MB 77.3 kB/s eta 0:26:11
   ---------------------------------------- 0.4/121.9 MB 77.3 kB/s eta 0:26:11
   ---------------------------------------- 0.4/121.9 MB 80.2 kB/s eta 0:25:14
   ---------------------------------------- 0.5/121.9 MB 81.4 kB/s eta 0:24:52
   ---------------------------------------- 0.5/121.9 MB 84.5 kB/s eta 0:23:58
   ---------------------------------------- 0.5/121.9 MB 87.5 kB/s eta 0:23:08
   ---------------------------------------- 0.5/121.9 MB 88.6 kB/s eta 0:22:50
   ---------------------------------------- 0.5/121.9 MB 91.8 kB/s eta 0:22:03
   ---------------------------------------- 0.6/121.9 MB 95.7 kB/s eta 0:21:09
   ---------------------------------------- 0.6/121.9 MB 98.7 kB/s eta 0:20:29
   ---------------------------------------- 0.6/121.9 MB 99.7 kB/s eta 0:20:17
   ---------------------------------------- 0.6/121.9 MB 102.7 kB/s eta 0:19:41
   ---------------------------------------- 0.6/121.9 MB 106.6 kB/s eta 0:18:58
   ---------------------------------------- 0.7/121.9 MB 109.5 kB/s eta 0:18:28
   ---------------------------------------- 0.7/121.9 MB 113.5 kB/s eta 0:17:48
   ---------------------------------------- 0.7/121.9 MB 114.9 kB/s eta 0:17:35
   ---------------------------------------- 0.7/121.9 MB 122.2 kB/s eta 0:16:32
   ---------------------------------------- 0.8/121.9 MB 126.3 kB/s eta 0:15:59
   ---------------------------------------- 0.8/121.9 MB 132.1 kB/s eta 0:15:17
   ---------------------------------------- 0.9/121.9 MB 137.3 kB/s eta 0:14:42
   ---------------------------------------- 0.9/121.9 MB 140.3 kB/s eta 0:14:23
   ---------------------------------------- 0.9/121.9 MB 147.1 kB/s eta 0:13:43
   ---------------------------------------- 1.0/121.9 MB 150.8 kB/s eta 0:13:22
   ---------------------------------------- 1.0/121.9 MB 157.8 kB/s eta 0:12:47
   ---------------------------------------- 1.0/121.9 MB 161.4 kB/s eta 0:12:29
   ---------------------------------------- 1.1/121.9 MB 168.2 kB/s eta 0:11:59
   ---------------------------------------- 1.1/121.9 MB 174.4 kB/s eta 0:11:33
   ---------------------------------------- 1.2/121.9 MB 178.3 kB/s eta 0:11:18
   ---------------------------------------- 1.2/121.9 MB 184.8 kB/s eta 0:10:53
   ---------------------------------------- 1.2/121.9 MB 185.9 kB/s eta 0:10:50
   ---------------------------------------- 1.3/121.9 MB 196.0 kB/s eta 0:10:16
   ---------------------------------------- 1.4/121.9 MB 202.2 kB/s eta 0:09:56
   ---------------------------------------- 1.4/121.9 MB 208.4 kB/s eta 0:09:39
   ---------------------------------------- 1.5/121.9 MB 215.9 kB/s eta 0:09:18
    --------------------------------------- 1.5/121.9 MB 221.9 kB/s eta 0:09:03
    --------------------------------------- 1.6/121.9 MB 228.3 kB/s eta 0:08:47
    --------------------------------------- 1.6/121.9 MB 235.1 kB/s eta 0:08:32
    --------------------------------------- 1.7/121.9 MB 243.7 kB/s eta 0:08:14
    --------------------------------------- 1.8/121.9 MB 250.8 kB/s eta 0:07:59
    --------------------------------------- 1.8/121.9 MB 257.8 kB/s eta 0:07:46
    --------------------------------------- 1.9/121.9 MB 266.1 kB/s eta 0:07:31
    --------------------------------------- 2.0/121.9 MB 272.9 kB/s eta 0:07:20
    --------------------------------------- 2.0/121.9 MB 281.7 kB/s eta 0:07:06
    --------------------------------------- 2.1/121.9 MB 291.9 kB/s eta 0:06:51
    --------------------------------------- 2.2/121.9 MB 299.8 kB/s eta 0:06:40
    --------------------------------------- 2.3/121.9 MB 309.0 kB/s eta 0:06:28
    --------------------------------------- 2.4/121.9 MB 318.7 kB/s eta 0:06:16
    --------------------------------------- 2.5/121.9 MB 327.7 kB/s eta 0:06:05
    --------------------------------------- 2.5/121.9 MB 336.5 kB/s eta 0:05:55
    --------------------------------------- 2.6/121.9 MB 345.9 kB/s eta 0:05:45
    --------------------------------------- 2.7/121.9 MB 348.6 kB/s eta 0:05:43
    --------------------------------------- 2.8/121.9 MB 366.4 kB/s eta 0:05:25
    --------------------------------------- 2.9/121.9 MB 376.2 kB/s eta 0:05:17
    --------------------------------------- 3.0/121.9 MB 384.5 kB/s eta 0:05:10
   - -------------------------------------- 3.1/121.9 MB 395.3 kB/s eta 0:05:01
   - -------------------------------------- 3.2/121.9 MB 406.0 kB/s eta 0:04:53
   - -------------------------------------- 3.3/121.9 MB 417.9 kB/s eta 0:04:44
   - -------------------------------------- 3.4/121.9 MB 429.6 kB/s eta 0:04:36
   - -------------------------------------- 3.6/121.9 MB 443.7 kB/s eta 0:04:27
   - -------------------------------------- 3.6/121.9 MB 453.5 kB/s eta 0:04:21
   - -------------------------------------- 3.8/121.9 MB 466.4 kB/s eta 0:04:14
   - -------------------------------------- 3.9/121.9 MB 480.2 kB/s eta 0:04:06
   - -------------------------------------- 4.1/121.9 MB 495.0 kB/s eta 0:03:59
   - -------------------------------------- 4.2/121.9 MB 508.3 kB/s eta 0:03:52
   - -------------------------------------- 4.3/121.9 MB 524.0 kB/s eta 0:03:45
   - -------------------------------------- 4.5/121.9 MB 538.3 kB/s eta 0:03:39
   - -------------------------------------- 4.6/121.9 MB 552.4 kB/s eta 0:03:33
   - -------------------------------------- 4.8/121.9 MB 568.8 kB/s eta 0:03:26
   - -------------------------------------- 5.0/121.9 MB 585.0 kB/s eta 0:03:20
   - -------------------------------------- 5.1/121.9 MB 601.1 kB/s eta 0:03:15
   - -------------------------------------- 5.3/121.9 MB 618.1 kB/s eta 0:03:09
   - -------------------------------------- 5.5/121.9 MB 637.5 kB/s eta 0:03:03
   - -------------------------------------- 5.7/121.9 MB 654.2 kB/s eta 0:02:58
   - -------------------------------------- 5.8/121.9 MB 670.7 kB/s eta 0:02:54
   - -------------------------------------- 6.0/121.9 MB 689.4 kB/s eta 0:02:49
   -- ------------------------------------- 6.2/121.9 MB 710.2 kB/s eta 0:02:43
   -- ------------------------------------- 6.5/121.9 MB 730.8 kB/s eta 0:02:38
   -- ------------------------------------- 6.6/121.9 MB 748.9 kB/s eta 0:02:34
   -- ------------------------------------- 6.9/121.9 MB 770.3 kB/s eta 0:02:30
   -- ------------------------------------- 7.1/121.9 MB 790.2 kB/s eta 0:02:26
   -- ------------------------------------- 7.3/121.9 MB 811.2 kB/s eta 0:02:22
   -- ------------------------------------- 7.5/121.9 MB 833.1 kB/s eta 0:02:18
   -- ------------------------------------- 7.8/121.9 MB 855.8 kB/s eta 0:02:14
   -- ------------------------------------- 8.0/121.9 MB 876.0 kB/s eta 0:02:10
   -- ------------------------------------- 8.3/121.9 MB 900.5 kB/s eta 0:02:07
   -- ------------------------------------- 8.5/121.9 MB 920.3 kB/s eta 0:02:04
   -- ------------------------------------- 8.8/121.9 MB 946.6 kB/s eta 0:02:00
   -- ------------------------------------- 9.1/121.9 MB 969.2 kB/s eta 0:01:57
   --- ------------------------------------ 9.3/121.9 MB 994.0 kB/s eta 0:01:54
   --- ------------------------------------ 9.6/121.9 MB 1.0 MB/s eta 0:01:50
   --- ------------------------------------ 9.9/121.9 MB 1.0 MB/s eta 0:01:47
   --- ------------------------------------ 10.2/121.9 MB 1.1 MB/s eta 0:01:45
   --- ------------------------------------ 10.3/121.9 MB 1.1 MB/s eta 0:01:39
   --- ------------------------------------ 10.6/121.9 MB 2.2 MB/s eta 0:00:50
   --- ------------------------------------ 10.7/121.9 MB 2.5 MB/s eta 0:00:46
   --- ------------------------------------ 10.7/121.9 MB 2.5 MB/s eta 0:00:46
   --- ------------------------------------ 11.2/121.9 MB 2.9 MB/s eta 0:00:38
   --- ------------------------------------ 11.5/121.9 MB 3.2 MB/s eta 0:00:35
   --- ------------------------------------ 11.9/121.9 MB 3.6 MB/s eta 0:00:31
   ---- ----------------------------------- 12.3/121.9 MB 3.9 MB/s eta 0:00:29
   ---- ----------------------------------- 12.6/121.9 MB 4.1 MB/s eta 0:00:27
   ---- ----------------------------------- 12.9/121.9 MB 4.3 MB/s eta 0:00:26
   ---- ----------------------------------- 13.2/121.9 MB 4.5 MB/s eta 0:00:25
   ---- ----------------------------------- 13.5/121.9 MB 4.6 MB/s eta 0:00:24
   ---- ----------------------------------- 13.8/121.9 MB 4.8 MB/s eta 0:00:23
   ---- ----------------------------------- 14.1/121.9 MB 5.0 MB/s eta 0:00:22
   ---- ----------------------------------- 14.3/121.9 MB 5.1 MB/s eta 0:00:22
   ---- ----------------------------------- 14.3/121.9 MB 5.1 MB/s eta 0:00:22
   ---- ----------------------------------- 14.3/121.9 MB 5.1 MB/s eta 0:00:22
   ---- ----------------------------------- 14.3/121.9 MB 5.1 MB/s eta 0:00:22
   ---- ----------------------------------- 14.4/121.9 MB 4.7 MB/s eta 0:00:23
   ---- ----------------------------------- 14.4/121.9 MB 4.7 MB/s eta 0:00:23
   ---- ----------------------------------- 14.4/121.9 MB 4.7 MB/s eta 0:00:23
   ---- ----------------------------------- 14.4/121.9 MB 4.7 MB/s eta 0:00:23
   ---- ----------------------------------- 14.4/121.9 MB 4.7 MB/s eta 0:00:23
   ---- ----------------------------------- 14.5/121.9 MB 4.3 MB/s eta 0:00:25

In [1]:
import sys
!{sys.executable} -m pip install "sentence-transformers==2.7.0" "transformers==4.39.3" --force-reinstall

Collecting sentence-transformers==2.7.0
  Using cached sentence_transformers-2.7.0-py3-none-any.whl.metadata (11 kB)
Collecting transformers==4.39.3
  Using cached transformers-4.39.3-py3-none-any.whl.metadata (134 kB)
Collecting tqdm (from sentence-transformers==2.7.0)
  Using cached tqdm-4.68.4-py3-none-any.whl.metadata (57 kB)
Collecting torch>=1.11.0 (from sentence-transformers==2.7.0)
  Using cached torch-2.13.0-cp311-cp311-win_amd64.whl.metadata (39 kB)
Collecting numpy (from sentence-transformers==2.7.0)
  Using cached numpy-2.4.6-cp311-cp311-win_amd64.whl.metadata (6.6 kB)
Collecting scikit-learn (from sentence-transformers==2.7.0)
  Using cached scikit_learn-1.9.0-cp311-cp311-win_amd64.whl.metadata (11 kB)
Collecting scipy (from sentence-transformers==2.7.0)
  Using cached scipy-1.17.1-cp311-cp311-win_amd64.whl.metadata (60 kB)
Collecting huggingface-hub>=0.15.1 (from sentence-transformers==2.7.0)
  Using cached huggingface_hub-1.22.0-py3-none-any.whl.metadata (14 kB)
Collecting Pillow (from sentence-transformers==2.7.0)
  Using cached pillow-12.3.0-cp311-cp311-win_amd64.whl.metadata (9.3 kB)
Collecting filelock (from transformers==4.39.3)
  Using cached filelock-3.29.7-py3-none-any.whl.metadata (2.0 kB)
Collecting huggingface-hub>=0.15.1 (from sentence-transformers==2.7.0)
  Using cached huggingface_hub-0.36.2-py3-none-any.whl.metadata (15 kB)
Collecting packaging>=20.0 (from transformers==4.39.3)
  Using cached packaging-26.2-py3-none-any.whl.metadata (3.5 kB)
Collecting pyyaml>=5.1 (from transformers==4.39.3)
  Using cached pyyaml-6.0.3-cp311-cp311-win_amd64.whl.metadata (2.4 kB)
Collecting regex!=2019.12.17 (from transformers==4.39.3)
  Using cached regex-2026.6.28-cp311-cp311-win_amd64.whl.metadata (41 kB)
Collecting requests (from transformers==4.39.3)
  Using cached requests-2.34.2-py3-none-any.whl.metadata (4.8 kB)
Collecting tokenizers<0.19,>=0.14 (from transformers==4.39.3)
  Using cached tokenizers-0.15.2-cp311-none-win_amd64.whl.metadata (6.8 kB)
Collecting safetensors>=0.4.1 (from transformers==4.39.3)
  Using cached safetensors-0.8.0-cp310-abi3-win_amd64.whl.metadata (4.2 kB)
Collecting fsspec>=2023.5.0 (from huggingface-hub>=0.15.1->sentence-transformers==2.7.0)
  Using cached fsspec-2026.6.0-py3-none-any.whl.metadata (10 kB)
Collecting typing-extensions>=3.7.4.3 (from huggingface-hub>=0.15.1->sentence-transformers==2.7.0)
  Using cached typing_extensions-4.16.0-py3-none-any.whl.metadata (3.3 kB)
Collecting setuptools>=77.0.3 (from torch>=1.11.0->sentence-transformers==2.7.0)
  Using cached setuptools-83.0.0-py3-none-any.whl.metadata (6.6 kB)
Collecting sympy>=1.13.3 (from torch>=1.11.0->sentence-transformers==2.7.0)
  Using cached sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
Collecting networkx>=2.5.1 (from torch>=1.11.0->sentence-transformers==2.7.0)
  Using cached networkx-3.6.1-py3-none-any.whl.metadata (6.8 kB)
Collecting jinja2 (from torch>=1.11.0->sentence-transformers==2.7.0)
  Using cached jinja2-3.1.6-py3-none-any.whl.metadata (2.9 kB)
Collecting colorama (from tqdm->sentence-transformers==2.7.0)
  Using cached colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Collecting charset_normalizer<4,>=2 (from requests->transformers==4.39.3)
  Using cached charset_normalizer-3.4.9-cp311-cp311-win_amd64.whl.metadata (42 kB)
Collecting idna<4,>=2.5 (from requests->transformers==4.39.3)
  Using cached idna-3.18-py3-none-any.whl.metadata (6.1 kB)
Collecting urllib3<3,>=1.26 (from requests->transformers==4.39.3)
  Using cached urllib3-2.7.0-py3-none-any.whl.metadata (6.9 kB)
Collecting certifi>=2023.5.7 (from requests->transformers==4.39.3)
  Using cached certifi-2026.6.17-py3-none-any.whl.metadata (2.5 kB)
Collecting joblib>=1.4.0 (from scikit-learn->sentence-transformers==2.7.0)
  Using cached joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting narwhals>=2.0.1 (from scikit-learn->sentence-transformers==2.7.0)
  Using cached narwhals-2.23.0-py3-none-any.whl.metadata (15 kB)
Collecting threadpoolctl>=3.5.0 (from scikit-learn->sentence-transformers==2.7.0)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Collecting mpmath<1.4,>=1.1.0 (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers==2.7.0)
  Using cached mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
Collecting MarkupSafe>=2.0 (from jinja2->torch>=1.11.0->sentence-transformers==2.7.0)
  Using cached markupsafe-3.0.3-cp311-cp311-win_amd64.whl.metadata (2.8 kB)
Using cached sentence_transformers-2.7.0-py3-none-any.whl (171 kB)
Using cached transformers-4.39.3-py3-none-any.whl (8.8 MB)
Using cached huggingface_hub-0.36.2-py3-none-any.whl (566 kB)
Using cached numpy-2.4.6-cp311-cp311-win_amd64.whl (12.6 MB)
Using cached packaging-26.2-py3-none-any.whl (100 kB)
Using cached pyyaml-6.0.3-cp311-cp311-win_amd64.whl (158 kB)
Using cached regex-2026.6.28-cp311-cp311-win_amd64.whl (277 kB)
Using cached safetensors-0.8.0-cp310-abi3-win_amd64.whl (355 kB)
Using cached tokenizers-0.15.2-cp311-none-win_amd64.whl (2.2 MB)
Using cached torch-2.13.0-cp311-cp311-win_amd64.whl (122.0 MB)
Using cached tqdm-4.68.4-py3-none-any.whl (676 kB)
Using cached filelock-3.29.7-py3-none-any.whl (46 kB)
Using cached pillow-12.3.0-cp311-cp311-win_amd64.whl (7.2 MB)
Using cached requests-2.34.2-py3-none-any.whl (73 kB)
Using cached scikit_learn-1.9.0-cp311-cp311-win_amd64.whl (8.3 MB)
Using cached scipy-1.17.1-cp311-cp311-win_amd64.whl (36.6 MB)
Using cached certifi-2026.6.17-py3-none-any.whl (133 kB)
Using cached charset_normalizer-3.4.9-cp311-cp311-win_amd64.whl (161 kB)
Using cached fsspec-2026.6.0-py3-none-any.whl (203 kB)
Using cached idna-3.18-py3-none-any.whl (65 kB)
Using cached joblib-1.5.3-py3-none-any.whl (309 kB)
Using cached narwhals-2.23.0-py3-none-any.whl (458 kB)
Using cached networkx-3.6.1-py3-none-any.whl (2.1 MB)
Using cached setuptools-83.0.0-py3-none-any.whl (1.0 MB)
Using cached sympy-1.14.0-py3-none-any.whl (6.3 MB)
Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Using cached typing_extensions-4.16.0-py3-none-any.whl (45 kB)
Using cached urllib3-2.7.0-py3-none-any.whl (131 kB)
Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Using cached jinja2-3.1.6-py3-none-any.whl (134 kB)
Using cached markupsafe-3.0.3-cp311-cp311-win_amd64.whl (15 kB)
Using cached mpmath-1.3.0-py3-none-any.whl (536 kB)
Installing collected packages: mpmath, urllib3, typing-extensions, threadpoolctl, sympy, setuptools, safetensors, regex, pyyaml, Pillow, packaging, numpy, networkx, narwhals, MarkupSafe, joblib, idna, fsspec, filelock, colorama, charset_normalizer, certifi, tqdm, scipy, requests, jinja2, torch, scikit-learn, huggingface-hub, tokenizers, transformers, sentence-transformers
  Attempting uninstall: mpmath
    Found existing installation: mpmath 1.3.0
    Uninstalling mpmath-1.3.0:
      Successfully uninstalled mpmath-1.3.0
  Attempting uninstall: urllib3
    Found existing installation: urllib3 2.7.0
    Uninstalling urllib3-2.7.0:
      Successfully uninstalled urllib3-2.7.0
  Attempting uninstall: typing-extensions
    Found existing installation: typing_extensions 4.16.0
    Uninstalling typing_extensions-4.16.0:
      Successfully uninstalled typing_extensions-4.16.0
  Attempting uninstall: threadpoolctl
    Found existing installation: threadpoolctl 3.6.0
    Uninstalling threadpoolctl-3.6.0:
      Successfully uninstalled threadpoolctl-3.6.0
  Attempting uninstall: sympy
    Found existing installation: sympy 1.14.0
    Uninstalling sympy-1.14.0:
      Successfully uninstalled sympy-1.14.0
  Attempting uninstall: setuptools
    Found existing installation: setuptools 83.0.0
    Uninstalling setuptools-83.0.0:
      Successfully uninstalled setuptools-83.0.0
  Attempting uninstall: safetensors
    Found existing installation: safetensors 0.8.0
    Uninstalling safetensors-0.8.0:
      Successfully uninstalled safetensors-0.8.0
  Attempting uninstall: regex
    Found existing installation: regex 2026.6.28
    Uninstalling regex-2026.6.28:
      Successfully uninstalled regex-2026.6.28
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 6.0.3
    Uninstalling PyYAML-6.0.3:
      Successfully uninstalled PyYAML-6.0.3
  Attempting uninstall: Pillow
    Found existing installation: pillow 12.3.0
    Uninstalling pillow-12.3.0:
      Successfully uninstalled pillow-12.3.0
  Attempting uninstall: packaging
    Found existing installation: packaging 26.2
    Uninstalling packaging-26.2:
      Successfully uninstalled packaging-26.2
  Attempting uninstall: numpy
    Found existing installation: numpy 2.4.6
    Uninstalling numpy-2.4.6:
      Successfully uninstalled numpy-2.4.6
  Attempting uninstall: networkx
    Found existing installation: networkx 3.6.1
    Uninstalling networkx-3.6.1:
      Successfully uninstalled networkx-3.6.1
  Attempting uninstall: narwhals
    Found existing installation: narwhals 2.23.0
    Uninstalling narwhals-2.23.0:
      Successfully uninstalled narwhals-2.23.0
  Attempting uninstall: MarkupSafe
    Found existing installation: MarkupSafe 3.0.3
    Uninstalling MarkupSafe-3.0.3:
      Successfully uninstalled MarkupSafe-3.0.3
  Attempting uninstall: joblib
    Found existing installation: joblib 1.5.3
    Uninstalling joblib-1.5.3:
      Successfully uninstalled joblib-1.5.3
  Attempting uninstall: idna
    Found existing installation: idna 3.18
    Uninstalling idna-3.18:
      Successfully uninstalled idna-3.18
  Attempting uninstall: fsspec
    Found existing installation: fsspec 2026.6.0
    Uninstalling fsspec-2026.6.0:
      Successfully uninstalled fsspec-2026.6.0
  Attempting uninstall: filelock
    Found existing installation: filelock 3.29.7
    Uninstalling filelock-3.29.7:
      Successfully uninstalled filelock-3.29.7
  Attempting uninstall: colorama
    Found existing installation: colorama 0.4.6
    Uninstalling colorama-0.4.6:
      Successfully uninstalled colorama-0.4.6
  Attempting uninstall: charset_normalizer
    Found existing installation: charset-normalizer 3.4.9
    Uninstalling charset-normalizer-3.4.9:
      Successfully uninstalled charset-normalizer-3.4.9
  Attempting uninstall: certifi
    Found existing installation: certifi 2026.6.17
    Uninstalling certifi-2026.6.17:
      Successfully uninstalled certifi-2026.6.17
  Attempting uninstall: tqdm
    Found existing installation: tqdm 4.68.4
    Uninstalling tqdm-4.68.4:
      Successfully uninstalled tqdm-4.68.4
  Attempting uninstall: scipy
    Found existing installation: scipy 1.17.1
    Uninstalling scipy-1.17.1:
      Successfully uninstalled scipy-1.17.1
  Attempting uninstall: requests
    Found existing installation: requests 2.34.2
    Uninstalling requests-2.34.2:
      Successfully uninstalled requests-2.34.2
  Attempting uninstall: jinja2
    Found existing installation: Jinja2 3.1.6
    Uninstalling Jinja2-3.1.6:
      Successfully uninstalled Jinja2-3.1.6
  Attempting uninstall: torch
    Found existing installation: torch 2.13.0
    Uninstalling torch-2.13.0:
      Successfully uninstalled torch-2.13.0
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.9.0
    Uninstalling scikit-learn-1.9.0:
      Successfully uninstalled scikit-learn-1.9.0
  Attempting uninstall: huggingface-hub
    Found existing installation: huggingface_hub 0.36.2
    Uninstalling huggingface_hub-0.36.2:
      Successfully uninstalled huggingface_hub-0.36.2
  Attempting uninstall: tokenizers
    Found existing installation: tokenizers 0.15.2
    Uninstalling tokenizers-0.15.2:
      Successfully uninstalled tokenizers-0.15.2
  Attempting uninstall: transformers
    Found existing installation: transformers 4.39.3
    Uninstalling transformers-4.39.3:
      Successfully uninstalled transformers-4.39.3
  Attempting uninstall: sentence-transformers
    Found existing installation: sentence-transformers 2.7.0
    Uninstalling sentence-transformers-2.7.0:
      Successfully uninstalled sentence-transformers-2.7.0
Successfully installed MarkupSafe-3.0.3 Pillow-12.3.0 certifi-2026.6.17 charset_normalizer-3.4.9 colorama-0.4.6 filelock-3.29.7 fsspec-2026.6.0 huggingface-hub-0.36.2 idna-3.18 jinja2-3.1.6 joblib-1.5.3 mpmath-1.3.0 narwhals-2.23.0 networkx-3.6.1 numpy-2.4.6 packaging-26.2 pyyaml-6.0.3 regex-2026.6.28 requests-2.34.2 safetensors-0.8.0 scikit-learn-1.9.0 scipy-1.17.1 sentence-transformers-2.7.0 setuptools-83.0.0 sympy-1.14.0 threadpoolctl-3.6.0 tokenizers-0.15.2 torch-2.13.0 tqdm-4.68.4 transformers-4.39.3 typing-extensions-4.16.0 urllib3-2.7.0

  WARNING: Failed to remove contents in a temporary directory 'C:\Users\famil\anaconda3\Lib\site-packages\~aml'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\famil\anaconda3\Lib\site-packages\~~mpy.libs'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\famil\AppData\Local\Temp\pip-uninstall-sb6hrtvd'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\famil\anaconda3\Lib\site-packages\~arkupsafe'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\famil\AppData\Local\Temp\pip-uninstall-uvffwylr'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\famil\anaconda3\Lib\site-packages\~harset_normalizer'.
  You can safely remove it manually.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
conda-repo-cli 1.0.75 requires requests_mock, which is not installed.
gensim 4.3.0 requires FuzzyTM>=0.4.0, which is not installed.
anaconda-cloud-auth 0.1.4 requires pydantic<2.0, but you have pydantic 2.12.5 which is incompatible.
astropy 5.3.4 requires numpy<2,>=1.21, but you have numpy 2.4.6 which is incompatible.
botocore 1.31.64 requires urllib3<2.1,>=1.25.4; python_version >= "3.10", but you have urllib3 2.7.0 which is incompatible.
conda-repo-cli 1.0.75 requires clyent==1.2.1, but you have clyent 1.2.2 which is incompatible.
conda-repo-cli 1.0.75 requires PyYAML==6.0.1, but you have pyyaml 6.0.3 which is incompatible.
conda-repo-cli 1.0.75 requires requests==2.31.0, but you have requests 2.34.2 which is incompatible.
contourpy 1.2.0 requires numpy<2.0,>=1.20, but you have numpy 2.4.6 which is incompatible.
crewai 1.6.1 requires tokenizers>=0.20.3, but you have tokenizers 0.15.2 which is incompatible.
gradio 6.0.1 requires pydantic<=2.12.4,>=2.11.10, but you have pydantic 2.12.5 which is incompatible.
langchain 0.1.16 requires numpy<2,>=1, but you have numpy 2.4.6 which is incompatible.
langchain-community 0.0.38 requires numpy<2,>=1, but you have numpy 2.4.6 which is incompatible.
langchain-core 0.1.53 requires packaging<24.0,>=23.2, but you have packaging 26.2 which is incompatible.
matplotlib 3.8.0 requires numpy<2,>=1.21, but you have numpy 2.4.6 which is incompatible.
numba 0.59.0 requires numpy<1.27,>=1.22, but you have numpy 2.4.6 which is incompatible.
pandas 2.1.4 requires numpy<2,>=1.23.2; python_version == "3.11", but you have numpy 2.4.6 which is incompatible.
pywavelets 1.5.0 requires numpy<2.0,>=1.22.4, but you have numpy 2.4.6 which is incompatible.
s3fs 2023.10.0 requires fsspec==2023.10.0, but you have fsspec 2026.6.0 which is incompatible.
streamlit 1.51.0 requires packaging<26,>=20, but you have packaging 26.2 which is incompatible.
streamlit 1.51.0 requires pyarrow<22,>=7.0, but you have pyarrow 23.0.1 which is incompatible.
textual 8.2.0 requires rich>=14.2.0, but you have rich 13.9.4 which is incompatible.

In [20]:
import sys
!{sys.executable} -m pip install --upgrade --force-reinstall numpy pandas

Collecting numpy

WARNING: Skipping C:\Users\famil\anaconda3\Lib\site-packages\numpy-1.26.4.dist-info due to invalid metadata entry 'name'
WARNING: Skipping C:\Users\famil\anaconda3\Lib\site-packages\numpy-1.26.4.dist-info due to invalid metadata entry 'name'
WARNING: Skipping C:\Users\famil\anaconda3\Lib\site-packages\numpy-1.26.4.dist-info due to invalid metadata entry 'name'
    WARNING: Skipping C:\Users\famil\anaconda3\Lib\site-packages\numpy-1.26.4.dist-info due to invalid metadata entry 'name'
    WARNING: Skipping C:\Users\famil\anaconda3\Lib\site-packages\numpy-1.26.4.dist-info due to invalid metadata entry 'name'
    WARNING: Skipping C:\Users\famil\anaconda3\Lib\site-packages\numpy-1.26.4.dist-info due to invalid metadata entry 'name'
    WARNING: Skipping C:\Users\famil\anaconda3\Lib\site-packages\numpy-1.26.4.dist-info due to invalid metadata entry 'name'
    WARNING: Skipping C:\Users\famil\anaconda3\Lib\site-packages\numpy-1.26.4.dist-info due to invalid metadata entry 'name'
WARNING: Skipping C:\Users\famil\anaconda3\Lib\site-packages\numpy-1.26.4.dist-info due to invalid metadata entry 'name'
WARNING: Skipping C:\Users\famil\anaconda3\Lib\site-packages\numpy-1.26.4.dist-info due to invalid metadata entry 'name'
WARNING: Skipping C:\Users\famil\anaconda3\Lib\site-packages\numpy-1.26.4.dist-info due to invalid metadata entry 'name'
WARNING: Skipping C:\Users\famil\anaconda3\Lib\site-packages\numpy-1.26.4.dist-info due to invalid metadata entry 'name'
WARNING: Skipping C:\Users\famil\anaconda3\Lib\site-packages\numpy-1.26.4.dist-info due to invalid metadata entry 'name'
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
conda-repo-cli 1.0.75 requires requests_mock, which is not installed.
gensim 4.3.0 requires FuzzyTM>=0.4.0, which is not installed.
astropy 5.3.4 requires numpy<2,>=1.21, but you have numpy 2.4.6 which is incompatible.
botocore 1.31.64 requires urllib3<2.1,>=1.25.4; python_version >= "3.10", but you have urllib3 2.7.0 which is incompatible.
conda-repo-cli 1.0.75 requires clyent==1.2.1, but you have clyent 1.2.2 which is incompatible.
conda-repo-cli 1.0.75 requires python-dateutil==2.8.2, but you have python-dateutil 2.9.0.post0 which is incompatible.
conda-repo-cli 1.0.75 requires PyYAML==6.0.1, but you have pyyaml 6.0.3 which is incompatible.
conda-repo-cli 1.0.75 requires requests==2.31.0, but you have requests 2.34.2 which is incompatible.
contourpy 1.2.0 requires numpy<2.0,>=1.20, but you have numpy 2.4.6 which is incompatible.
crewai 1.6.1 requires tokenizers>=0.20.3, but you have tokenizers 0.15.2 which is incompatible.
gradio 6.0.1 requires pandas<3.0,>=1.0, but you have pandas 3.0.3 which is incompatible.
gradio 6.0.1 requires pydantic<=2.12.4,>=2.11.10, but you have pydantic 2.12.5 which is incompatible.
langchain 0.1.16 requires numpy<2,>=1, but you have numpy 2.4.6 which is incompatible.
langchain-community 0.0.38 requires numpy<2,>=1, but you have numpy 2.4.6 which is incompatible.
pywavelets 1.5.0 requires numpy<2.0,>=1.22.4, but you have numpy 2.4.6 which is incompatible.
streamlit 1.16.0 requires protobuf<4,>=3.12, but you have protobuf 5.29.6 which is incompatible.
WARNING: Skipping C:\Users\famil\anaconda3\Lib\site-packages\numpy-1.26.4.dist-info due to invalid metadata entry 'name'
WARNING: Skipping C:\Users\famil\anaconda3\Lib\site-packages\numpy-1.26.4.dist-info due to invalid metadata entry 'name'
WARNING: Skipping C:\Users\famil\anaconda3\Lib\site-packages\numpy-1.26.4.dist-info due to invalid metadata entry 'name'

  Using cached numpy-2.4.6-cp311-cp311-win_amd64.whl.metadata (6.6 kB)
Collecting pandas
  Using cached pandas-3.0.3-cp311-cp311-win_amd64.whl.metadata (19 kB)
Collecting python-dateutil>=2.8.2 (from pandas)
  Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
Collecting tzdata (from pandas)
  Using cached tzdata-2026.2-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting six>=1.5 (from python-dateutil>=2.8.2->pandas)
  Using cached six-1.17.0-py2.py3-none-any.whl.metadata (1.7 kB)
Using cached numpy-2.4.6-cp311-cp311-win_amd64.whl (12.6 MB)
Using cached pandas-3.0.3-cp311-cp311-win_amd64.whl (9.9 MB)
Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
Using cached tzdata-2026.2-py2.py3-none-any.whl (349 kB)
Using cached six-1.17.0-py2.py3-none-any.whl (11 kB)
Installing collected packages: tzdata, six, numpy, python-dateutil, pandas
  Attempting uninstall: tzdata
    Found existing installation: tzdata 2026.2
    Uninstalling tzdata-2026.2:
      Successfully uninstalled tzdata-2026.2
  Attempting uninstall: six
    Found existing installation: six 1.17.0
    Uninstalling six-1.17.0:
      Successfully uninstalled six-1.17.0
  Attempting uninstall: numpy
    Found existing installation: numpy 2.4.6
    Uninstalling numpy-2.4.6:
      Successfully uninstalled numpy-2.4.6
  Attempting uninstall: python-dateutil
    Found existing installation: python-dateutil 2.9.0.post0
    Uninstalling python-dateutil-2.9.0.post0:
      Successfully uninstalled python-dateutil-2.9.0.post0
  Attempting uninstall: pandas
    Found existing installation: pandas 3.0.3
    Uninstalling pandas-3.0.3:
      Successfully uninstalled pandas-3.0.3
Successfully installed numpy-2.4.6 pandas-3.0.3 python-dateutil-2.9.0.post0 six-1.17.0 tzdata-2026.2

In [ ]:
import pandas as pd

knowledge_base_clean = pd.read_csv("../data/knowledge_base_cleaned.csv")
chunks_df = pd.read_csv("../data/chunks.csv")

print("Knowledge base reloaded:", knowledge_base_clean.shape)
print("Chunks reloaded:", chunks_df.shape)

In [17]:
import pandas

ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

In [5]:
import sys
print(sys.executable)

C:\Users\famil\anaconda3\python.exe

In [6]:
import numpy
print(numpy.__version__)

2.4.6

In [7]:
pip show numpy

Name: numpy
Version: 1.26.4
Summary: Fundamental package for array computing in Python
Home-page: https://numpy.org
Author: Travis E. Oliphant et al.
Author-email:
License: Copyright (c) 2005-2023, NumPy Developers.
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are
met:

    * Redistributions of source code must retain the above copyright
       notice, this list of conditions and the following disclaimer.

    * Redistributions in binary form must reproduce the above
       copyright notice, this list of conditions and the following
       disclaimer in the documentation and/or other materials provided
       with the distribution.

    * Neither the name of the NumPy Developers nor the names of any
       contributors may be used to endorse or promote products derived
       from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

----

The NumPy repository and source distributions bundle several libraries that are
compatibly licensed.  We list these here.

Name: lapack-lite
Files: numpy/linalg/lapack_lite/*
License: BSD-3-Clause
  For details, see numpy/linalg/lapack_lite/LICENSE.txt

Name: tempita
Files: tools/npy_tempita/*
License: MIT
  For details, see tools/npy_tempita/license.txt

Name: dragon4
Files: numpy/core/src/multiarray/dragon4.c
License: MIT
  For license text, see numpy/core/src/multiarray/dragon4.c

Name: libdivide
Files: numpy/core/include/numpy/libdivide/*
License: Zlib
  For license text, see numpy/core/include/numpy/libdivide/LICENSE.txt


Note that the following files are vendored in the repository and sdist but not
installed in built numpy packages:

Name: Meson
Files: vendored-meson/meson/*
License: Apache 2.0
  For license text, see vendored-meson/meson/COPYING

Name: spin
Files: .spin/cmds.py
License: BSD-3
  For license text, see .spin/LICENSE

----

This binary distribution of NumPy also bundles the following software:


Name: OpenBLAS
Files: numpy.libs\libopenblas*.dll
Description: bundled as a dynamically linked library
Availability: https://github.com/OpenMathLib/OpenBLAS/
License: BSD-3-Clause
  Copyright (c) 2011-2014, The OpenBLAS Project
  All rights reserved.

  Redistribution and use in source and binary forms, with or without
  modification, are permitted provided that the following conditions are
  met:

     1. Redistributions of source code must retain the above copyright
        notice, this list of conditions and the following disclaimer.

     2. Redistributions in binary form must reproduce the above copyright
        notice, this list of conditions and the following disclaimer in
        the documentation and/or other materials provided with the
        distribution.
     3. Neither the name of the OpenBLAS project nor the names of
        its contributors may be used to endorse or promote products
        derived from this software without specific prior written
        permission.

  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
  ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
  DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
  SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
  CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
  OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
  USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


Name: LAPACK
Files: numpy.libs\libopenblas*.dll
Description: bundled in OpenBLAS
Availability: https://github.com/OpenMathLib/OpenBLAS/
License: BSD-3-Clause-Attribution
  Copyright (c) 1992-2013 The University of Tennessee and The University
                          of Tennessee Research Foundation.  All rights
                          reserved.
  Copyright (c) 2000-2013 The University of California Berkeley. All
                          rights reserved.
  Copyright (c) 2006-2013 The University of Colorado Denver.  All rights
                          reserved.

  $COPYRIGHT$

  Additional copyrights may follow

  $HEADER$

  Redistribution and use in source and binary forms, with or without
  modification, are permitted provided that the following conditions are
  met:

  - Redistributions of source code must retain the above copyright
    notice, this list of conditions and the following disclaimer.

  - Redistributions in binary form must reproduce the above copyright
    notice, this list of conditions and the following disclaimer listed
    in this license in the documentation and/or other materials
    provided with the distribution.

  - Neither the name of the copyright holders nor the names of its
    contributors may be used to endorse or promote products derived from
    this software without specific prior written permission.

  The copyright holders provide no reassurances that the source code
  provided does not infringe any patent, copyright, or any other
  intellectual property rights of third parties.  The copyright holders
  disclaim any liability to any recipient for claims brought against
  recipient by any third party for infringement of that parties
  intellectual property rights.

  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


Name: GCC runtime library
Files: numpy.libs\libopenblas*.dll
Description: statically linked to files compiled with gcc
Availability: https://gcc.gnu.org/git/?p=gcc.git;a=tree;f=libgfortran
License: GPL-3.0-with-GCC-exception
  Copyright (C) 2002-2017 Free Software Foundation, Inc.

  Libgfortran is free software; you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation; either version 3, or (at your option)
  any later version.

  Libgfortran is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  Under Section 7 of GPL version 3, you are granted additional
  permissions described in the GCC Runtime Library Exception, version
  3.1, as published by the Free Software Foundation.

  You should have received a copy of the GNU General Public License and
  a copy of the GCC Runtime Library Exception along with this program;
  see the files COPYING3 and COPYING.RUNTIME respectively.  If not, see
  <http://www.gnu.org/licenses/>.

----

Full text of license texts referred to above follows (that they are
listed below does not necessarily imply the conditions apply to the
present binary release):

----

GCC RUNTIME LIBRARY EXCEPTION

Version 3.1, 31 March 2009

Copyright (C) 2009 Free Software Foundation, Inc. <http://fsf.org/>

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

This GCC Runtime Library Exception ("Exception") is an additional
permission under section 7 of the GNU General Public License, version
3 ("GPLv3"). It applies to a given file (the "Runtime Library") that
bears a notice placed by the copyright holder of the file stating that
the file is governed by GPLv3 along with this Exception.

When you use GCC to compile a program, GCC may combine portions of
certain GCC header files and runtime libraries with the compiled
program. The purpose of this Exception is to allow compilation of
non-GPL (including proprietary) programs to use, in this way, the
header files and runtime libraries covered by this Exception.

0. Definitions.

A file is an "Independent Module" if it either requires the Runtime
Library for execution after a Compilation Process, or makes use of an
interface provided by the Runtime Library, but is not otherwise based
on the Runtime Library.

"GCC" means a version of the GNU Compiler Collection, with or without
modifications, governed by version 3 (or a specified later version) of
the GNU General Public License (GPL) with the option of using any
subsequent versions published by the FSF.

"GPL-compatible Software" is software whose conditions of propagation,
modification and use would permit combination with GCC in accord with
the license of GCC.

"Target Code" refers to output from any compiler for a real or virtual
target processor architecture, in executable form or suitable for
input to an assembler, loader, linker and/or execution
phase. Notwithstanding that, Target Code does not include data in any
format that is used as a compiler intermediate representation, or used
for producing a compiler intermediate representation.

The "Compilation Process" transforms code entirely represented in
non-intermediate languages designed for human-written code, and/or in
Java Virtual Machine byte code, into Target Code. Thus, for example,
use of source code generators and preprocessors need not be considered
part of the Compilation Process, since the Compilation Process can be
understood as starting with the output of the generators or
preprocessors.

A Compilation Process is "Eligible" if it is done using GCC, alone or
with other GPL-compatible software, or if it is done without using any
work based on GCC. For example, using non-GPL-compatible Software to
optimize any GCC intermediate representations would not qualify as an
Eligible Compilation Process.

1. Grant of Additional Permission.

You have permission to propagate a work of Target Code formed by
combining the Runtime Library with Independent Modules, even if such
propagation would otherwise violate the terms of GPLv3, provided that
all Target Code was generated by Eligible Compilation Processes. You
may then convey such a combination under terms of your choice,
consistent with the licensing of the Independent Modules.

2. No Weakening of GCC Copyleft.

The availability of this Exception does not imply any general
presumption that third-party software is unaffected by the copyleft
requirements of the license of GCC.

----

                    GNU GENERAL PUBLIC LICENSE
                       Version 3, 29 June 2007

 Copyright (C) 2007 Free Software Foundation, Inc. <http://fsf.org/>
 Everyone is permitted to copy and distribute verbatim copies
 of this license document, but changing it is not allowed.

                            Preamble

  The GNU General Public License is a free, copyleft license for
software and other kinds of works.

  The licenses for most software and other practical works are designed
to take away your freedom to share and change the works.  By contrast,
the GNU General Public License is intended to guarantee your freedom to
share and change all versions of a program--to make sure it remains free
software for all its users.  We, the Free Software Foundation, use the
GNU General Public License for most of our software; it applies also to
any other work released this way by its authors.  You can apply it to
your programs, too.

  When we speak of free software, we are referring to freedom, not
price.  Our General Public Licenses are designed to make sure that you
have the freedom to distribute copies of free software (and charge for
them if you wish), that you receive source code or can get it if you
want it, that you can change the software or use pieces of it in new
free programs, and that you know you can do these things.

  To protect your rights, we need to prevent others from denying you
these rights or asking you to surrender the rights.  Therefore, you have
certain responsibilities if you distribute copies of the software, or if
you modify it: responsibilities to respect the freedom of others.

  For example, if you distribute copies of such a program, whether
gratis or for a fee, you must pass on to the recipients the same
freedoms that you received.  You must make sure that they, too, receive
or can get the source code.  And you must show them these terms so they
know their rights.

  Developers that use the GNU GPL protect your rights with two steps:
(1) assert copyright on the software, and (2) offer you this License
giving you legal permission to copy, distribute and/or modify it.

  For the developers' and authors' protection, the GPL clearly explains
that there is no warranty for this free software.  For both users' and
authors' sake, the GPL requires that modified versions be marked as
changed, so that their problems will not be attributed erroneously to
authors of previous versions.

  Some devices are designed to deny users access to install or run
modified versions of the software inside them, although the manufacturer
can do so.  This is fundamentally incompatible with the aim of
protecting users' freedom to change the software.  The systematic
pattern of such abuse occurs in the area of products for individuals to
use, which is precisely where it is most unacceptable.  Therefore, we
have designed this version of the GPL to prohibit the practice for those
products.  If such problems arise substantially in other domains, we
stand ready to extend this provision to those domains in future versions
of the GPL, as needed to protect the freedom of users.

  Finally, every program is threatened constantly by software patents.
States should not allow patents to restrict development and use of
software on general-purpose computers, but in those that do, we wish to
avoid the special danger that patents applied to a free program could
make it effectively proprietary.  To prevent this, the GPL assures that
patents cannot be used to render the program non-free.

  The precise terms and conditions for copying, distribution and
modification follow.

                       TERMS AND CONDITIONS

  0. Definitions.

  "This License" refers to version 3 of the GNU General Public License.

  "Copyright" also means copyright-like laws that apply to other kinds of
works, such as semiconductor masks.

  "The Program" refers to any copyrightable work licensed under this
License.  Each licensee is addressed as "you".  "Licensees" and
"recipients" may be individuals or organizations.

  To "modify" a work means to copy from or adapt all or part of the work
in a fashion requiring copyright permission, other than the making of an
exact copy.  The resulting work is called a "modified version" of the
earlier work or a work "based on" the earlier work.

  A "covered work" means either the unmodified Program or a work based
on the Program.

  To "propagate" a work means to do anything with it that, without
permission, would make you directly or secondarily liable for
infringement under applicable copyright law, except executing it on a
computer or modifying a private copy.  Propagation includes copying,
distribution (with or without modification), making available to the
public, and in some countries other activities as well.

  To "convey" a work means any kind of propagation that enables other
parties to make or receive copies.  Mere interaction with a user through
a computer network, with no transfer of a copy, is not conveying.

  An interactive user interface displays "Appropriate Legal Notices"
to the extent that it includes a convenient and prominently visible
feature that (1) displays an appropriate copyright notice, and (2)
tells the user that there is no warranty for the work (except to the
extent that warranties are provided), that licensees may convey the
work under this License, and how to view a copy of this License.  If
the interface presents a list of user commands or options, such as a
menu, a prominent item in the list meets this criterion.

  1. Source Code.

  The "source code" for a work means the preferred form of the work
for making modifications to it.  "Object code" means any non-source
form of a work.

  A "Standard Interface" means an interface that either is an official
standard defined by a recognized standards body, or, in the case of
interfaces specified for a particular programming language, one that
is widely used among developers working in that language.

  The "System Libraries" of an executable work include anything, other
than the work as a whole, that (a) is included in the normal form of
packaging a Major Component, but which is not part of that Major
Component, and (b) serves only to enable use of the work with that
Major Component, or to implement a Standard Interface for which an
implementation is available to the public in source code form.  A
"Major Component", in this context, means a major essential component
(kernel, window system, and so on) of the specific operating system
(if any) on which the executable work runs, or a compiler used to
produce the work, or an object code interpreter used to run it.

  The "Corresponding Source" for a work in object code form means all
the source code needed to generate, install, and (for an executable
work) run the object code and to modify the work, including scripts to
control those activities.  However, it does not include the work's
System Libraries, or general-purpose tools or generally available free
programs which are used unmodified in performing those activities but
which are not part of the work.  For example, Corresponding Source
includes interface definition files associated with source files for
the work, and the source code for shared libraries and dynamically
linked subprograms that the work is specifically designed to require,
such as by intimate data communication or control flow between those
subprograms and other parts of the work.

  The Corresponding Source need not include anything that users
can regenerate automatically from other parts of the Corresponding
Source.

  The Corresponding Source for a work in source code form is that
same work.

  2. Basic Permissions.

  All rights granted under this License are granted for the term of
copyright on the Program, and are irrevocable provided the stated
conditions are met.  This License explicitly affirms your unlimited
permission to run the unmodified Program.  The output from running a
covered work is covered by this License only if the output, given its
content, constitutes a covered work.  This License acknowledges your
rights of fair use or other equivalent, as provided by copyright law.


In [8]:
pip show pandas

Name: pandas
Version: 2.1.4
Summary: Powerful data structures for data analysis, time series, and statistics
Home-page: https://pandas.pydata.org
Author:
Author-email: The Pandas Development Team <pandas-dev@python.org>
License: BSD 3-Clause License

Copyright (c) 2008-2011, AQR Capital Management, LLC, Lambda Foundry, Inc. and PyData Development Team
All rights reserved.

Copyright (c) 2011-2023, Open source contributors.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

* Redistributions of source code must retain the above copyright notice, this
  list of conditions and the following disclaimer.

* Redistributions in binary form must reproduce the above copyright notice,
  this list of conditions and the following disclaimer in the documentation
  and/or other materials provided with the distribution.

* Neither the name of the copyright holder nor the names of its
  contributors may be used to endorse or promote products derived from
  this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Location: C:\Users\famil\anaconda3\Lib\site-packages
Requires: numpy, python-dateutil, pytz, tzdata
Required-by: altair, bokeh, cufflinks, datashader, gradio, holoviews, hvplot, mlxtend, panel, seaborn, statsmodels, streamlit, xarray
Note: you may need to restart the kernel to use updated packages.

In [19]:
import numpy
print(numpy.__version__)

2.4.6

In [5]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(max_features=384, stop_words='english')

embeddings = vectorizer.fit_transform(chunks_df['chunk_text'])

print("Embeddings shape:", embeddings.shape)

Embeddings shape: (56862, 384)

# Task 10 : Chroma DB

In [6]:
import sys
!{sys.executable} -m pip install chromadb

Requirement already satisfied: chromadb in c:\users\famil\anaconda3\lib\site-packages (1.1.1)
Requirement already satisfied: build>=1.0.3 in c:\users\famil\anaconda3\lib\site-packages (from chromadb) (1.3.0)
Requirement already satisfied: pydantic>=1.9 in c:\users\famil\anaconda3\lib\site-packages (from chromadb) (2.12.5)
Requirement already satisfied: pybase64>=1.4.1 in c:\users\famil\anaconda3\lib\site-packages (from chromadb) (1.4.3)
Requirement already satisfied: uvicorn>=0.18.3 in c:\users\famil\anaconda3\lib\site-packages (from uvicorn[standard]>=0.18.3->chromadb) (0.38.0)
Requirement already satisfied: numpy>=1.22.5 in c:\users\famil\anaconda3\lib\site-packages (from chromadb) (2.4.6)
Requirement already satisfied: posthog<6.0.0,>=2.4.0 in c:\users\famil\anaconda3\lib\site-packages (from chromadb) (5.4.0)
Requirement already satisfied: typing-extensions>=4.5.0 in c:\users\famil\anaconda3\lib\site-packages (from chromadb) (4.16.0)
Requirement already satisfied: onnxruntime>=1.14.1 in c:\users\famil\anaconda3\lib\site-packages (from chromadb) (1.24.4)
Requirement already satisfied: opentelemetry-api>=1.2.0 in c:\users\famil\anaconda3\lib\site-packages (from chromadb) (1.34.1)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-grpc>=1.2.0 in c:\users\famil\anaconda3\lib\site-packages (from chromadb) (1.34.1)
Requirement already satisfied: opentelemetry-sdk>=1.2.0 in c:\users\famil\anaconda3\lib\site-packages (from chromadb) (1.34.1)
Requirement already satisfied: tokenizers>=0.13.2 in c:\users\famil\anaconda3\lib\site-packages (from chromadb) (0.15.2)
Requirement already satisfied: pypika>=0.48.9 in c:\users\famil\anaconda3\lib\site-packages (from chromadb) (0.51.1)
Requirement already satisfied: tqdm>=4.65.0 in c:\users\famil\anaconda3\lib\site-packages (from chromadb) (4.68.4)
Requirement already satisfied: overrides>=7.3.1 in c:\users\famil\anaconda3\lib\site-packages (from chromadb) (7.4.0)
Requirement already satisfied: importlib-resources in c:\users\famil\anaconda3\lib\site-packages (from chromadb) (6.5.2)
Requirement already satisfied: grpcio>=1.58.0 in c:\users\famil\anaconda3\lib\site-packages (from chromadb) (1.76.0)
Requirement already satisfied: bcrypt>=4.0.1 in c:\users\famil\anaconda3\lib\site-packages (from chromadb) (5.0.0)
Requirement already satisfied: typer>=0.9.0 in c:\users\famil\anaconda3\lib\site-packages (from chromadb) (0.20.0)
Requirement already satisfied: kubernetes>=28.1.0 in c:\users\famil\anaconda3\lib\site-packages (from chromadb) (35.0.0)
Requirement already satisfied: tenacity>=8.2.3 in c:\users\famil\anaconda3\lib\site-packages (from chromadb) (8.5.0)
Requirement already satisfied: pyyaml>=6.0.0 in c:\users\famil\anaconda3\lib\site-packages (from chromadb) (6.0.3)
Requirement already satisfied: mmh3>=4.0.1 in c:\users\famil\anaconda3\lib\site-packages (from chromadb) (5.2.1)
Requirement already satisfied: orjson>=3.9.12 in c:\users\famil\anaconda3\lib\site-packages (from chromadb) (3.11.4)
Requirement already satisfied: httpx>=0.27.0 in c:\users\famil\anaconda3\lib\site-packages (from chromadb) (0.28.1)
Requirement already satisfied: rich>=10.11.0 in c:\users\famil\anaconda3\lib\site-packages (from chromadb) (13.9.4)
Requirement already satisfied: jsonschema>=4.19.0 in c:\users\famil\anaconda3\lib\site-packages (from chromadb) (4.26.0)
Requirement already satisfied: packaging>=19.1 in c:\users\famil\anaconda3\lib\site-packages (from build>=1.0.3->chromadb) (26.0)
Requirement already satisfied: pyproject_hooks in c:\users\famil\anaconda3\lib\site-packages (from build>=1.0.3->chromadb) (1.2.0)
Requirement already satisfied: colorama in c:\users\famil\anaconda3\lib\site-packages (from build>=1.0.3->chromadb) (0.4.6)
Requirement already satisfied: anyio in c:\users\famil\anaconda3\lib\site-packages (from httpx>=0.27.0->chromadb) (4.13.0)
Requirement already satisfied: certifi in c:\users\famil\anaconda3\lib\site-packages (from httpx>=0.27.0->chromadb) (2026.6.17)
Requirement already satisfied: httpcore==1.* in c:\users\famil\anaconda3\lib\site-packages (from httpx>=0.27.0->chromadb) (1.0.9)
Requirement already satisfied: idna in c:\users\famil\anaconda3\lib\site-packages (from httpx>=0.27.0->chromadb) (3.18)
Requirement already satisfied: h11>=0.16 in c:\users\famil\anaconda3\lib\site-packages (from httpcore==1.*->httpx>=0.27.0->chromadb) (0.16.0)
Requirement already satisfied: attrs>=22.2.0 in c:\users\famil\anaconda3\lib\site-packages (from jsonschema>=4.19.0->chromadb) (23.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\famil\anaconda3\lib\site-packages (from jsonschema>=4.19.0->chromadb) (2023.7.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\famil\anaconda3\lib\site-packages (from jsonschema>=4.19.0->chromadb) (0.30.2)
Requirement already satisfied: rpds-py>=0.25.0 in c:\users\famil\anaconda3\lib\site-packages (from jsonschema>=4.19.0->chromadb) (0.30.0)
Requirement already satisfied: six>=1.9.0 in c:\users\famil\anaconda3\lib\site-packages (from kubernetes>=28.1.0->chromadb) (1.17.0)
Requirement already satisfied: python-dateutil>=2.5.3 in c:\users\famil\anaconda3\lib\site-packages (from kubernetes>=28.1.0->chromadb) (2.9.0.post0)
Requirement already satisfied: websocket-client!=0.40.0,!=0.41.*,!=0.42.*,>=0.32.0 in c:\users\famil\anaconda3\lib\site-packages (from kubernetes>=28.1.0->chromadb) (0.58.0)
Requirement already satisfied: requests in c:\users\famil\anaconda3\lib\site-packages (from kubernetes>=28.1.0->chromadb) (2.34.2)
Requirement already satisfied: requests-oauthlib in c:\users\famil\anaconda3\lib\site-packages (from kubernetes>=28.1.0->chromadb) (2.0.0)
Requirement already satisfied: urllib3!=2.6.0,>=1.24.2 in c:\users\famil\anaconda3\lib\site-packages (from kubernetes>=28.1.0->chromadb) (2.7.0)
Requirement already satisfied: durationpy>=0.7 in c:\users\famil\anaconda3\lib\site-packages (from kubernetes>=28.1.0->chromadb) (0.10)
Requirement already satisfied: flatbuffers in c:\users\famil\anaconda3\lib\site-packages (from onnxruntime>=1.14.1->chromadb) (25.12.19)
Requirement already satisfied: protobuf in c:\users\famil\anaconda3\lib\site-packages (from onnxruntime>=1.14.1->chromadb) (5.29.6)
Requirement already satisfied: sympy in c:\users\famil\anaconda3\lib\site-packages (from onnxruntime>=1.14.1->chromadb) (1.14.0)
Requirement already satisfied: importlib-metadata<8.8.0,>=6.0 in c:\users\famil\anaconda3\lib\site-packages (from opentelemetry-api>=1.2.0->chromadb) (7.0.1)
Requirement already satisfied: googleapis-common-protos~=1.52 in c:\users\famil\anaconda3\lib\site-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (1.73.1)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-common==1.34.1 in c:\users\famil\anaconda3\lib\site-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (1.34.1)
Requirement already satisfied: opentelemetry-proto==1.34.1 in c:\users\famil\anaconda3\lib\site-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (1.34.1)
Requirement already satisfied: opentelemetry-semantic-conventions==0.55b1 in c:\users\famil\anaconda3\lib\site-packages (from opentelemetry-sdk>=1.2.0->chromadb) (0.55b1)
Requirement already satisfied: backoff>=1.10.0 in c:\users\famil\anaconda3\lib\site-packages (from posthog<6.0.0,>=2.4.0->chromadb) (2.2.1)
Requirement already satisfied: distro>=1.5.0 in c:\users\famil\anaconda3\lib\site-packages (from posthog<6.0.0,>=2.4.0->chromadb) (1.9.0)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\famil\anaconda3\lib\site-packages (from pydantic>=1.9->chromadb) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in c:\users\famil\anaconda3\lib\site-packages (from pydantic>=1.9->chromadb) (2.41.5)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\famil\anaconda3\lib\site-packages (from pydantic>=1.9->chromadb) (0.4.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\famil\anaconda3\lib\site-packages (from rich>=10.11.0->chromadb) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\famil\anaconda3\lib\site-packages (from rich>=10.11.0->chromadb) (2.19.2)
Requirement already satisfied: huggingface_hub<1.0,>=0.16.4 in c:\users\famil\anaconda3\lib\site-packages (from tokenizers>=0.13.2->chromadb) (0.36.2)
Requirement already satisfied: click>=8.0.0 in c:\users\famil\anaconda3\lib\site-packages (from typer>=0.9.0->chromadb) (8.4.2)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\famil\anaconda3\lib\site-packages (from typer>=0.9.0->chromadb) (1.5.4)
Requirement already satisfied: httptools>=0.6.3 in c:\users\famil\anaconda3\lib\site-packages (from uvicorn[standard]>=0.18.3->chromadb) (0.7.1)
Requirement already satisfied: python-dotenv>=0.13 in c:\users\famil\anaconda3\lib\site-packages (from uvicorn[standard]>=0.18.3->chromadb) (1.1.1)
Requirement already satisfied: watchfiles>=0.13 in c:\users\famil\anaconda3\lib\site-packages (from uvicorn[standard]>=0.18.3->chromadb) (1.1.1)
Requirement already satisfied: websockets>=10.4 in c:\users\famil\anaconda3\lib\site-packages (from uvicorn[standard]>=0.18.3->chromadb) (16.0)
Requirement already satisfied: filelock in c:\users\famil\anaconda3\lib\site-packages (from huggingface_hub<1.0,>=0.16.4->tokenizers>=0.13.2->chromadb) (3.29.7)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\famil\anaconda3\lib\site-packages (from huggingface_hub<1.0,>=0.16.4->tokenizers>=0.13.2->chromadb) (2026.1.0)
Requirement already satisfied: zipp>=0.5 in c:\users\famil\anaconda3\lib\site-packages (from importlib-metadata<8.8.0,>=6.0->opentelemetry-api>=1.2.0->chromadb) (3.17.0)
Requirement already satisfied: mdurl~=0.1 in c:\users\famil\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->chromadb) (0.1.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\famil\anaconda3\lib\site-packages (from requests->kubernetes>=28.1.0->chromadb) (3.4.9)
Requirement already satisfied: oauthlib>=3.0.0 in c:\users\famil\anaconda3\lib\site-packages (from requests-oauthlib->kubernetes>=28.1.0->chromadb) (3.3.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\famil\anaconda3\lib\site-packages (from sympy->onnxruntime>=1.14.1->chromadb) (1.3.0)

WARNING: Skipping C:\Users\famil\anaconda3\Lib\site-packages\numpy-1.26.4.dist-info due to invalid metadata entry 'name'
WARNING: Skipping C:\Users\famil\anaconda3\Lib\site-packages\numpy-1.26.4.dist-info due to invalid metadata entry 'name'
WARNING: Skipping C:\Users\famil\anaconda3\Lib\site-packages\numpy-1.26.4.dist-info due to invalid metadata entry 'name'
WARNING: Skipping C:\Users\famil\anaconda3\Lib\site-packages\numpy-1.26.4.dist-info due to invalid metadata entry 'name'
WARNING: Skipping C:\Users\famil\anaconda3\Lib\site-packages\numpy-1.26.4.dist-info due to invalid metadata entry 'name'
WARNING: Skipping C:\Users\famil\anaconda3\Lib\site-packages\numpy-1.26.4.dist-info due to invalid metadata entry 'name'

In [7]:
import chromadb

client = chromadb.Client()
collection = client.create_collection(name="bug_knowledge_base")

# Convert TF-IDF sparse matrix to lists for ChromaDB
embeddings_list = embeddings.toarray().tolist()

# Add in batches (ChromaDB works better with reasonable batch sizes)
batch_size = 5000
for i in range(0, len(chunks_df), batch_size):
    batch_end = min(i + batch_size, len(chunks_df))
    collection.add(
        ids=chunks_df['chunk_id'].iloc[i:batch_end].tolist(),
        embeddings=embeddings_list[i:batch_end],
        documents=chunks_df['chunk_text'].iloc[i:batch_end].tolist(),
        metadatas=chunks_df[['bug_id', 'title', 'severity', 'resolution', 'status', 'source_dataset']].iloc[i:batch_end].to_dict('records')
    )
    print(f"Added batch {i} to {batch_end}")

print("Total items in collection:", collection.count())

Added batch 0 to 5000
Added batch 5000 to 10000
Added batch 10000 to 15000
Added batch 15000 to 20000
Added batch 20000 to 25000
Added batch 25000 to 30000
Added batch 30000 to 35000
Added batch 35000 to 40000
Added batch 40000 to 45000
Added batch 45000 to 50000
Added batch 50000 to 55000
Added batch 55000 to 56862
Total items in collection: 56862

In [9]:
client.delete_collection(name="bug_knowledge_base")  # remove the broken one

collection = client.create_collection(
    name="bug_knowledge_base",
    metadata={"hnsw:space": "cosine"}
)

In [10]:
# Convert TF-IDF sparse matrix to lists for ChromaDB
embeddings_list = embeddings.toarray().tolist()

# Add in batches
batch_size = 5000
for i in range(0, len(chunks_df), batch_size):
    batch_end = min(i + batch_size, len(chunks_df))
    collection.add(
        ids=chunks_df['chunk_id'].iloc[i:batch_end].tolist(),
        embeddings=embeddings_list[i:batch_end],
        documents=chunks_df['chunk_text'].iloc[i:batch_end].tolist(),
        metadatas=chunks_df[['bug_id', 'title', 'severity', 'resolution', 'status', 'source_dataset']].iloc[i:batch_end].to_dict('records')
    )
    print(f"Added batch {i} to {batch_end}")

print("Total items in collection:", collection.count())

Added batch 0 to 5000
Added batch 5000 to 10000
Added batch 10000 to 15000
Added batch 15000 to 20000
Added batch 20000 to 25000
Added batch 25000 to 30000
Added batch 30000 to 35000
Added batch 35000 to 40000
Added batch 40000 to 45000
Added batch 45000 to 50000
Added batch 50000 to 55000
Added batch 55000 to 56862
Total items in collection: 56862

In [13]:
import numpy as np

print("Non-zero values in query vector:", np.count_nonzero(query_vector))
print("Query vector shape:", np.array(query_vector).shape)

# Which of our query words actually made it into the vocabulary?
vocab = vectorizer.vocabulary_
for word in ["application", "crashes", "crash", "login", "special", "characters", "character", "password"]:
    print(word, "->", "IN VOCAB" if word in vocab else "NOT in vocab")

Non-zero values in query vector: 1
Query vector shape: (1, 384)
application -> IN VOCAB
crashes -> NOT in vocab
crash -> IN VOCAB
login -> NOT in vocab
special -> NOT in vocab
characters -> NOT in vocab
character -> NOT in vocab
password -> NOT in vocab

In [14]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(max_features=3000, stop_words='english')
embeddings = vectorizer.fit_transform(chunks_df['chunk_text'])

print("Embeddings shape:", embeddings.shape)

Embeddings shape: (56862, 3000)

In [15]:
client.delete_collection(name="bug_knowledge_base")
collection = client.create_collection(
    name="bug_knowledge_base",
    metadata={"hnsw:space": "cosine"}
)

embeddings_list = embeddings.toarray().tolist()

batch_size = 5000
for i in range(0, len(chunks_df), batch_size):
    batch_end = min(i + batch_size, len(chunks_df))
    collection.add(
        ids=chunks_df['chunk_id'].iloc[i:batch_end].tolist(),
        embeddings=embeddings_list[i:batch_end],
        documents=chunks_df['chunk_text'].iloc[i:batch_end].tolist(),
        metadatas=chunks_df[['bug_id', 'title', 'severity', 'resolution', 'status', 'source_dataset']].iloc[i:batch_end].to_dict('records')
    )
    print(f"Added batch {i} to {batch_end}")

print("Total items in collection:", collection.count())

Added batch 0 to 5000
Added batch 5000 to 10000
Added batch 10000 to 15000
Added batch 15000 to 20000
Added batch 20000 to 25000
Added batch 25000 to 30000
Added batch 30000 to 35000
Added batch 35000 to 40000
Added batch 40000 to 45000
Added batch 45000 to 50000
Added batch 50000 to 55000
Added batch 55000 to 56862
Total items in collection: 56862

# Task 11

In [16]:
query_text = "application crashes on login with special characters in password"
query_vector = vectorizer.transform([query_text]).toarray().tolist()

results = collection.query(
    query_embeddings=query_vector,
    n_results=5
)

for i in range(len(results['ids'][0])):
    print(f"Match {i+1}: {results['metadatas'][0][i]['title']}")
    print(f"  Severity: {results['metadatas'][0][i]['severity']} | Source: {results['metadatas'][0][i]['source_dataset']}")
    print()

Match 1: Special characters don't show up on config page
  Severity: normal | Source: Mozilla

Match 2: Java applet password field gains focus but cannot be typed in.
  Severity: major | Source: Mozilla

Match 3: Login Fails if token is reset while waiting for a password.
  Severity: normal | Source: Mozilla

Match 4: [pwd-mngr] Password incorrectly stored
  Severity: minor | Source: Mozilla

Match 5: [pwd-mngr] Password incorrectly stored
  Severity: minor | Source: Mozilla